export default [
  {
    adjusterName: 'Arthur Dent',
    adjusterNumber: '(555) 226-7709',
    cashTag: '',
    chargesDue: '$100.00',
    claimNumber: '123121321',
    clientUpdateTime: '2018-01-15T16: 47: 14Z',
    colors: 'GOLD',
    damageCode: 'FR',
    description: '16 AUDI A7 PRESTIG GOLD',
    destination: {
      accurate: true,
      city: 'HOUSTON',
      crossstreet: 'USA',
      exists: true,
      lat: 29.9685949,
      line1: '1655 RANKIN ROAD',
      line2: '',
      lng: -95.37359819999999,
      name: 'TX - HOUSTON',
      pano_id: 'YD4jHCnSbHoHpqDhw01sdA',
      partial_match: true,
      state: 'TX',
      zip: '77073',
      zpp: '',
    },
    destinationLocationId: 'yard-11',
    dispatch_status: 'A',
    insuredName: 'Ford Prefect',
    isPartialTripLot: false,
    isTowable: 'Y',
    jobUpdateTime: '2018-01-10T19: 38: 27Z',
    lossDate: '2016-11-13',
    lossType: 'C - COLLISION',
    lotStage: 20,
    lotTripId: 7111833752,
    make: 'AUDI',
    model: 'A7 PRESTIG',
    number: 17207346,
    ownerName: 'Ford Prefect',
    ownerNumber: '(567)834-5687',
    policyNumber: '45352718',
    pickupNotes: ' It is a mistake to think you can solve any major problems just with potatoes.',
    pickupPhoneNumber: {
      areaCode: '713',
      extension: '',
      line: '5234774',
    },
    promisedTripDate: '2016-11-15',
    responsible_party_name: 'Bruce Wayne',
    tripId: 'vipaul-1516034834183',
    scheduledTimeFrom: '',
    scheduledTimeTo: '',
    selectedByUser: 'vipaul',
    sellerName: 'Zaphod B.',
    sellerNumber: 'AM42',
    sellerReference: '',
    source: {
      availibility: {
        days: 'Mon-Fri',
        hours: '6am - 7pm',
      },
      accurate: true,
      city: 'HOUSTON',
      crossstreet: '',
      exists: true,
      lat: 29.7240933,
      line1: '5329 KIRBY DR.',
      line2: '',
      lng: -95.4179858,
      name: 'RIVER OAKS PAINT&BODY',
      pano_id: 'ZSGzwxz5CxIEp7xO9Ql5wQ',
      partial_match: true,
      residence: 'Y',
      state: 'TX',
      zip: '77005',
      zpp: '',
      paymentTypesAccepted: {
        card: true,
        check: true,
        cash: true,
      },
    },
    sourceLocationId: 'loc-3129398101',
    subhaulerUser: 'A & S TOW',
    suffix: 'X',
    towType: 'S',
    trackupdatedBy: 'CALL FOR RELEASE',
    tripStatus: 'W',
    tripType: 'D',
    tripZone: 5,
    updateByUser: 'OPSPORTAL-vipaul',
    updatedBy: 'realtime',
    // vehicleType: 'V - AUTOMOBILE',
    vehicleType: 'A',
    yardNumber: 11,
    year: 2016,
    forms: {},
    status: 'assigned',
    issue: {},
  },
  {
    cashTag: '',
    chargesDue: '$100.00',
    clientUpdateTime: '2018-01-16T02: 30: 07Z',
    colors: 'SILVR',
    damageCode: 'NW',
    description: '04 SAA 9-3 SILVR',
    destination: {
      accurate: true,
      city: 'HOUSTON',
      crossstreet: 'USA',
      exists: true,
      lat: 29.9685949,
      line1: '1655 RANKIN ROAD',
      line2: '',
      lng: -95.37359819999999,
      name: 'TX - HOUSTON',
      pano_id: 'YD4jHCnSbHoHpqDhw01sdA',
      partial_match: true,
      state: 'TX',
      zip: '77073',
      zpp: '',
    },
    destinationLocationId: 'yard-11',
    dispatch_status: 'A',
    isPartialTripLot: false,
    isTowable: 'Y',
    jobUpdateTime: '2016-02-10T17: 11: 29Z',
    lossType: 'D - DONATION',
    lotStage: 20,
    lotTripId: 7111892155,
    make: 'SAA',
    model: '9-3',
    number: 17214376,
    pickupNotes:
      'In the beginning the Universe was created. This has made a lot of people very angry and been widely regarded as a bad move.',
    pickupPhoneNumber: {
      areaCode: '281',
      extension: '',
      line: '9892723',
    },
    promisedTripDate: '2017-12-14',
    responsible_party_name: 'Clark Kent',
    tripId: 'cxgandla-1516069807120',
    scheduledTimeFrom: '',
    scheduledTimeTo: '',
    sellerNumber: 'WFW1',
    sellerReference: '',
    source: {
      accurate: true,
      city: 'HOUSTON',
      crossstreet: '',
      exists: true,
      lat: 29.6950587,
      line1: '7818 BARBERTON DR',
      line2: '',
      lng: -95.5254204,
      name: 'JOHN LACAMU',
      pano_id: 'vGb-_mVphDWKxHW5QfNCww',
      partial_match: false,
      residence: 'N',
      state: 'TX',
      zip: '77036',
      zpp: '',
      paymentTypesAccepted: {
        card: true,
        check: false,
        cash: false,
      },
    },
    sourceLocationId: 'loc-7111892153',
    subhaulerUser: 'A & S TOW',
    suffix: 'X',
    towType: 'Standard',
    trackupdatedBy: 'CALL FOR RELEASE',
    tripStatus: 'W',
    tripType: 'P',
    tripZone: 5,
    updateByUser: 'OPSPORTAL-cxgandla',
    updatedBy: 'realtime',
    vehicleType: 'V',
    yardNumber: 11,
    year: 2004,
    forms: {},
    status: 'assigned',
    issue: {},
  },
  {
    cashTag: '',
    chargesDue: '$100.00',
    clientUpdateTime: '2018-01-16T02: 30: 07Z',
    colors: 'BLACK',
    damageCode: 'AO',
    description: '98 ACUR CSX BLACK',
    destination: {
      accurate: true,
      city: 'HOUSTON',
      crossstreet: 'USA',
      exists: true,
      lat: 29.9685949,
      line1: '1655 RANKIN ROAD',
      line2: '',
      lng: -95.37359819999999,
      name: 'TX - HOUSTON',
      pano_id: 'YD4jHCnSbHoHpqDhw01sdA',
      partial_match: true,
      state: 'TX',
      zip: '77073',
      zpp: '',
    },
    destinationLocationId: 'yard-11',
    dispatch_status: 'A',
    isPartialTripLot: false,
    isTowable: 'N',
    jobUpdateTime: '2017-11-30T07: 58: 29Z',
    lossType: 'D - DONATION',
    lotStage: 20,
    lotTripId: 7241866640,
    make: 'ACUR',
    model: 'CSX',
    number: 51743917,
    pickupNotes:
      'One morning, when Gregor Samsa woke from troubled dreams, he found himself transformed in his bed into a horrible vermin. He lay on his armour-like back, and if he lifted his head a little he could see his brown belly, slightly domed and divided by arches into stiff sections. The bedding was hardly able to cover it and seemed ready to slide off any moment. His many legs, pitifully thin compared with the size of the rest of him, waved about helplessly as he looked. "What\'s happened to me?" he thought. It wasn\'t a dream. His room, a proper human room although a little too small, lay peacefully between its four familiar walls. A collection of textile samples lay spread out on the table - Samsa was a travelling salesman - and above it there hung a picture that he had recently cut out of an illustrated magazine and housed in a nice, gilded frame. It showed a lady fitted out with a fur hat and fur boa who sat upright, raising a heavy fur muff that covered the whole of her lower arm towards the viewer. Gregor then turned to look out the window at the dull weather. Drops of rain could be heard hitting the pane, which made him feel quite sad.\n\nOne morning, when Gregor Samsa woke from troubled dreams, he found himself transformed in his bed into a horrible vermin. He lay on his armour-like back, and if he lifted his head a little he could see his brown belly, slightly domed and divided by arches into stiff sections. The bedding was hardly able to cover it and seemed ready to slide off any moment. His many legs, pitifully thin compared with the size of the rest of him, waved about helplessly as he looked. "What\'s happened to me?" he thought. It wasn\'t a dream. His room, a proper human room although a little too small, lay peacefully between its four familiar walls. A collection of textile samples lay spread out on the table - Samsa was a travelling salesman - and above it there hung a picture that he had recently cut out of an illustrated magazine and housed in a nice, gilded frame. It showed a lady fitted out with a fur hat and fur boa who sat upright, raising a heavy fur muff that covered the whole of her lower arm towards the viewer. Gregor then turned to look out the window at the dull weather. Drops of rain could be heard hitting the pane, which made him feel quite sad.',
    pickupPhoneNumber: {
      areaCode: '214',
      extension: '',
      line: '8375712',
    },
    promisedTripDate: '2017-12-13',
    responsible_party_name: 'Clark Kent',
    tripId: 'cxgandla-1516069807120',
    scheduledTimeFrom: '',
    scheduledTimeTo: '',
    sellerNumber: 'JST1',
    sellerReference: '',
    source: {
      availibility: {
        days: 'Mon-Fri',
        hours: '6am - 7pm',
      },
      accurate: true,
      city: 'DALLAS',
      crossstreet: '',
      exists: true,
      lat: 32.9872088,
      line1: '7650 MCCALLUM BLVD',
      line2: '',
      lng: -96.7754157,
      name: 'RESIDENCE',
      pano_id: '8AiVRb2LMDTVzGTwebfbdw',
      partial_match: true,
      residence: 'N',
      state: 'TX',
      zip: '75254',
      zpp: '',
      paymentTypesAccepted: {
        card: true,
        check: true,
        cash: true,
      },
    },
    sourceLocationId: 'loc-7243794327',
    subhaulerUser: 'A & S TOW',
    suffix: 'Q',
    towType: 'Standard',
    trackupdatedBy: 'CALL FOR RELEASE',
    tripStatus: 'W',
    tripType: 'P',
    tripZone: 43,
    updateByUser: 'OPSPORTAL-cxgandla',
    updatedBy: 'realtime',
    vehicleType: 'M',
    yardNumber: 11,
    year: 1998,
    forms: {},
    status: 'assigned',
    issue: {},
  },
  {
    cashTag: '',
    chargesDue: '$100.00',
    clientUpdateTime: '2018-01-16T19: 48: 21Z',
    colors: 'BLUE',
    damageCode: 'FR',
    description: '10 AUDI A4 BLUE',
    destination: {
      accurate: true,
      city: 'HOUSTON',
      crossstreet: 'USA',
      exists: true,
      lat: 29.9685949,
      line1: '1655 RANKIN ROAD',
      line2: '',
      lng: -95.37359819999999,
      name: 'TX - HOUSTON',
      pano_id: 'YD4jHCnSbHoHpqDhw01sdA',
      partial_match: true,
      state: 'TX',
      zip: '77073',
      zpp: '',
    },
    destinationLocationId: 'yard-11',
    dispatch_status: 'A',
    isPartialTripLot: false,
    isTowable: 'Y',
    jobUpdateTime: '2018-01-16T11: 48: 17Z',
    lossType: 'C - COLLISION',
    lotStage: 25,
    lotTripId: 7113755200,
    make: 'AUDI',
    model: 'A4',
    number: 17305116,
    pickupNotes: 'The Ultimate Answer to Life, The Universe and Everything is...42!',
    pickupPhoneNumber: {
      areaCode: '281',
      extension: '',
      line: '8727200',
    },
    promisedTripDate: '2016-11-22',
    responsible_party_name: 'Felicity Smoak',
    tripId: 'siparvatha-1516132096352',
    scheduledTimeFrom: '',
    scheduledTimeTo: '',
    sellerNumber: 'L106',
    sellerReference: '',
    source: {
      availibility: {
        days: 'Mon-Fri',
        hours: '6am - 7pm',
      },
      accurate: true,
      city: 'HOUSTON',
      crossstreet: '',
      exists: true,
      lat: 29.9705312,
      line1: '12600 KUYKENDAHL',
      line2: '',
      lng: -95.4237213,
      name: 'DEMONTROND AUTOMOTIVE',
      pano_id: 'iRs5CY0A5GpRvBpbyZ-aDQ',
      partial_match: true,
      residence: 'N',
      state: 'TX',
      zip: '77090',
      zpp: '',
      paymentTypesAccepted: {
        card: true,
        check: false,
        cash: true,
      },
    },
    sourceLocationId: 'loc-7113755199',
    subhaulerContact: {
      areaCode: '979',
      line: '3322345',
    },
    subhaulerUser: 'A & S TOW',
    suffix: 'X',
    towType: 'Standard',
    trackupdatedBy: 'CALL FOR RELEASE',
    tripStatus: 'W',
    tripType: 'P',
    tripZone: 2,
    updateByUser: 'REALTIME',
    updatedBy: 'realtime',
    vehicleType: 'D',
    yardNumber: 11,
    year: 2010,
    forms: {},
    status: 'assigned',
    issue: {},
  },
  {
    cashTag: '',
    chargesDue: '$100.00',
    clientUpdateTime: '2018-01-16T19: 48: 20Z',
    colors: 'WHITE',
    damageCode: 'FR',
    description: '08 JEP COMMANDER WHITE',
    destination: {
      accurate: true,
      city: 'HOUSTON',
      crossstreet: 'USA',
      exists: true,
      lat: 29.9685949,
      line1: '1655 RANKIN ROAD',
      line2: '',
      lng: -95.37359819999999,
      name: 'TX - HOUSTON',
      pano_id: 'YD4jHCnSbHoHpqDhw01sdA',
      partial_match: true,
      state: 'TX',
      zip: '77073',
      zpp: '',
    },
    destinationLocationId: 'yard-11',
    dispatch_status: 'A',
    isPartialTripLot: false,
    isTowable: 'Y',
    jobUpdateTime: '2018-01-16T11: 48: 17Z',
    lossType: 'C - COLLISION',
    lotStage: 25,
    lotTripId: 7117321363,
    make: 'JEP',
    model: 'COMMANDER',
    number: 17421426,
    pickupNotes:
      '"Exactly!" said Deep Thought. "So once you do know what the question actually is, you\'ll know what the answer means."',
    pickupPhoneNumber: {
      areaCode: '832',
      extension: '',
      line: '4432643',
    },
    promisedTripDate: '2016-11-21',
    responsible_party_name: 'Felicity Smoak',
    tripId: 'siparvatha-1516132096352',
    scheduledTimeFrom: '',
    scheduledTimeTo: '',
    sellerNumber: 'UST1',
    sellerReference: '',
    source: {
      availibility: {
        days: 'Mon-Fri',
        hours: '6am - 7pm',
      },
      accurate: true,
      city: 'HOUSTON',
      crossstreet: '',
      exists: true,
      lat: 29.8780049,
      line1: '11106 E. HARDY ROAD',
      line2: '',
      lng: -95.36589819999999,
      name: 'HCF PAINT & BODY',
      pano_id: 'okTr_n9Gb4nHlzp-uzlqqw',
      partial_match: true,
      residence: 'N',
      state: 'TX',
      zip: '77093',
      zpp: '',
      paymentTypesAccepted: {
        card: false,
        check: true,
        cash: true,
      },
    },
    sourceLocationId: 'loc-7117321362',
    subhaulerContact: {
      areaCode: '979',
      line: '3322345',
    },
    subhaulerUser: 'A & S TOW',
    suffix: 'X',
    towType: 'Standard',
    trackupdatedBy: 'CALL FOR RELEASE',
    tripStatus: 'W',
    tripType: 'P',
    tripZone: 3,
    updateByUser: 'REALTIME',
    updatedBy: 'realtime',
    vehicleType: 'U',
    yardNumber: 11,
    year: 2008,
    forms: {},
    status: 'assigned',
    issue: {},
  },
  {
    cashTag: '',
    chargesDue: '$100.00',
    clientUpdateTime: '2018-01-14T03: 02: 34Z',
    colors: 'BLACK',
    damageCode: 'AO',
    description: '12 HOND ACCORD BLACK',
    destination: {
      accurate: true,
      city: 'HOUSTON',
      crossstreet: 'USA',
      exists: true,
      lat: 29.9685949,
      line1: '1655 RANKIN ROAD',
      line2: '',
      lng: -95.37359819999999,
      name: 'TX - HOUSTON',
      pano_id: 'YD4jHCnSbHoHpqDhw01sdA',
      partial_match: true,
      state: 'TX',
      zip: '77073',
      zpp: '',
    },
    destinationLocationId: 'yard-11',
    dispatch_status: 'A',
    isPartialTripLot: false,
    isTowable: 'Y',
    jobUpdateTime: '2018-01-13T19: 02: 15Z',
    lossType: 'D - DONATION',
    lotStage: 28,
    lotTripId: 7243436557,
    make: 'HOND',
    model: 'ACCORD',
    number: 52389197,
    pickupNotes:
      'A common mistake that people make when trying to design something completely foolproof is to underestimate the ingenuity of complete fools.',
    pickupPhoneNumber: {
      areaCode: '915',
      extension: '',
      line: '8738481',
    },
    promisedTripDate: '2018-01-12',
    responsible_party_name: 'Caitlin Snow',
    tripId: 'SANATARAJA-1515898928654',
    scheduledTimeFrom: '',
    scheduledTimeTo: '',
    selectedByUser: 'SANATARAJA',
    sellerNumber: 'JST1',
    sellerReference: '',
    source: {
      availibility: {
        days: 'Mon-Fri',
        hours: '6am - 7pm',
      },
      accurate: true,
      city: 'CANUTILLO',
      crossstreet: '',
      exists: true,
      lat: 31.9554328,
      line1: '1350 BAYSHORE',
      line2: '',
      lng: -106.5743724,
      name: 'RESIDENCE',
      pano_id: 'a0fDRspIYWGweneEs--isA',
      partial_match: true,
      residence: 'N',
      state: 'TX',
      zip: '79835',
      zpp: '',
      paymentTypesAccepted: {
        card: true,
        check: true,
        cash: false,
      },
    },
    sourceLocationId: 'loc-7243212068',
    subhaulerContact: {
      areaCode: '979',
      line: '3322345',
    },
    subhaulerUser: 'A & S TOW',
    suffix: 'Q',
    towType: 'Standard',
    trackupdatedBy: 'CALL FOR RELEASE',
    tripStatus: 'P',
    tripType: 'P',
    tripZone: 99,
    updateByUser: 'REALTIME',
    updatedBy: 'realtime',
    vehicleType: 'E',
    yardNumber: 11,
    year: 2012,
    forms: {},
    status: 'assigned',
    issue: {},
  },
  {
    cashTag: '',
    chargesDue: '$100.00',
    clientUpdateTime: '2018-01-16T08: 07: 44Z',
    colors: 'BLACK',
    damageCode: 'AO',
    description: '12 HYUN ACCENT BLACK',
    destination: {
      accurate: true,
      city: 'HOUSTON',
      crossstreet: 'USA',
      exists: true,
      lat: 29.9685949,
      line1: '1655 RANKIN ROAD',
      line2: '',
      lng: -95.37359819999999,
      name: 'TX - HOUSTON',
      pano_id: 'YD4jHCnSbHoHpqDhw01sdA',
      partial_match: true,
      state: 'TX',
      zip: '77073',
      zpp: '',
    },
    destinationLocationId: 'yard-11',
    dispatch_status: 'A',
    isPartialTripLot: false,
    isTowable: 'Y',
    jobUpdateTime: '2018-01-16T00: 07: 39Z',
    lossType: 'D - DONATION',
    lotStage: 28,
    lotTripId: 7243467540,
    make: 'HYUN',
    model: 'ACCENT',
    number: 52398667,
    pickupNotes:
      'Curiously enough, the only thing that went through the mind of the bowl of petunias as it fell was Oh no, not again. Many people have speculated that if we knew exactly why the bowl of petunias had thought that we would know a lot more about the nature of the Universe than we do now.',
    pickupPhoneNumber: {
      areaCode: '915',
      extension: '',
      line: '8738481',
    },
    promisedTripDate: '2017-11-22',
    responsible_party_name: 'Oliver Queen',
    tripId: 'SHPANDEY-1516090055114',
    scheduledTimeFrom: '',
    scheduledTimeTo: '',
    sellerNumber: 'SBU1',
    sellerReference: '',
    source: {
      availibility: {
        days: 'Mon-Fri',
        hours: '6am - 7pm',
      },
      accurate: true,
      city: 'CANUTILLO',
      crossstreet: '',
      exists: true,
      lat: 31.9554328,
      line1: '1350 BAYSHORE',
      line2: '',
      lng: -106.5743724,
      name: 'RESIDENCE',
      pano_id: 'a0fDRspIYWGweneEs--isA',
      partial_match: true,
      residence: 'N',
      state: 'TX',
      zip: '79835',
      zpp: '',
      paymentTypesAccepted: {
        card: true,
        check: false,
        cash: false,
      },
    },
    sourceLocationId: 'loc-7243212068',
    subhaulerContact: {
      areaCode: '936',
      line: '4147845',
    },
    subhaulerUser: 'A & S TOW',
    suffix: 'Q',
    towType: 'Standard',
    trackupdatedBy: 'CALL FOR RELEASE',
    tripStatus: 'P',
    tripType: 'P',
    tripZone: 99,
    updateByUser: 'REALTIME',
    updatedBy: 'realtime',
    vehicleType: 'I',
    yardNumber: 11,
    year: 2012,
    forms: {},
    status: 'assigned',
    issue: {},
  },
  {
    cashTag: '',
    chargesDue: '$100.00',
    clientUpdateTime: '2018-01-16T18: 49: 49Z',
    colors: 'BLACK',
    damageCode: 'AO',
    description: '12 HYUN ACCENT BLACK',
    destination: {
      accurate: true,
      city: 'HOUSTON',
      crossstreet: 'USA',
      exists: true,
      lat: 29.9685949,
      line1: '1655 RANKIN ROAD',
      line2: '',
      lng: -95.37359819999999,
      name: 'TX - HOUSTON',
      pano_id: 'YD4jHCnSbHoHpqDhw01sdA',
      partial_match: true,
      state: 'TX',
      zip: '77073',
      zpp: '',
    },
    destinationLocationId: 'yard-11',
    dispatch_status: 'A',
    isPartialTripLot: false,
    isTowable: 'Y',
    jobUpdateTime: '2018-01-16T10: 49: 48Z',
    lossType: 'D - DONATION',
    lotStage: 25,
    lotTripId: 7243467610,
    make: 'HYUN',
    model: 'ACCENT',
    number: 52398857,
    pickupNotes:
      'The chances of finding out what’s really going on in the universe are so remote, the only thing to do is hang the sense of it and keep yourself occupied.',
    pickupPhoneNumber: {
      areaCode: '915',
      extension: '',
      line: '8738481',
    },
    promisedTripDate: '2017-11-22',
    responsible_party_name: 'Virgil Hawkins',
    tripId: 'srganja-1516128587950',
    scheduledTimeFrom: '',
    scheduledTimeTo: '',
    sellerNumber: 'SBU1',
    sellerReference: '',
    source: {
      availibility: {
        days: 'Mon-Fri',
        hours: '6am - 7pm',
      },
      accurate: true,
      city: 'CANUTILLO',
      crossstreet: '',
      exists: true,
      lat: 31.9554328,
      line1: '1350 BAYSHORE',
      line2: '',
      lng: -106.5743724,
      name: 'RESIDENCE',
      pano_id: 'a0fDRspIYWGweneEs--isA',
      partial_match: true,
      residence: 'N',
      state: 'TX',
      zip: '79835',
      zpp: '',
      paymentTypesAccepted: {
        card: false,
        check: true,
        cash: true,
      },
    },
    sourceLocationId: 'loc-7243212068',
    subhaulerContact: {
      areaCode: '713',
      line: '2596219',
    },
    subhaulerUser: 'A & S TOW',
    suffix: 'Q',
    towType: 'Standard',
    trackupdatedBy: 'CALL FOR RELEASE',
    tripStatus: 'W',
    tripType: 'P',
    tripZone: 99,
    updateByUser: 'REALTIME',
    updatedBy: 'realtime',
    vehicleType: 'J',
    yardNumber: 11,
    year: 2012,
    forms: {},
    status: 'assigned',
    issue: {},
  },
  {
    cashTag: '',
    chargesDue: '$100.00',
    clientUpdateTime: '2018-01-16T18: 49: 49Z',
    colors: 'BLACK',
    damageCode: 'AO',
    description: '12 KIA AMANTI BLACK',
    destination: {
      accurate: true,
      city: 'HOUSTON',
      crossstreet: 'USA',
      exists: true,
      lat: 29.9685949,
      line1: '1655 RANKIN ROAD',
      line2: '',
      lng: -95.37359819999999,
      name: 'TX - HOUSTON',
      pano_id: 'YD4jHCnSbHoHpqDhw01sdA',
      partial_match: true,
      state: 'TX',
      zip: '77073',
      zpp: '',
    },
    destinationLocationId: 'yard-11',
    dispatch_status: 'A',
    isPartialTripLot: false,
    isTowable: 'Y',
    jobUpdateTime: '2018-01-16T10: 49: 49Z',
    lossType: 'C - COLLISION',
    lotStage: 25,
    lotTripId: 7243796806,
    make: 'KIA',
    model: 'AMANTI',
    number: 52425447,
    pickupNotes: 'Is there any tea on this spaceship?',
    pickupPhoneNumber: {
      areaCode: '915',
      extension: '',
      line: '8738481',
    },
    promisedTripDate: '2017-12-04',
    responsible_party_name: 'Virgil Hawkins',
    tripId: 'srganja-1516128587950',
    scheduledTimeFrom: '',
    scheduledTimeTo: '',
    sellerNumber: 'SBU1',
    sellerReference: '',
    source: {
      availibility: {
        days: 'Mon-Fri',
        hours: '6am - 7pm',
      },
      accurate: true,
      city: 'CANUTILLO',
      crossstreet: '',
      exists: true,
      lat: 31.9554328,
      line1: '1350 BAYSHORE',
      line2: '',
      lng: -106.5743724,
      name: 'RESIDENCE',
      pano_id: 'a0fDRspIYWGweneEs--isA',
      partial_match: true,
      residence: 'N',
      state: 'TX',
      zip: '79835',
      zpp: '',
      paymentTypesAccepted: {
        card: true,
        check: false,
        cash: false,
      },
    },
    sourceLocationId: 'loc-7243212068',
    subhaulerContact: {
      areaCode: '713',
      line: '2596219',
    },
    subhaulerUser: 'A & S TOW',
    suffix: 'Q',
    towType: 'Standard',
    trackupdatedBy: 'CALL FOR RELEASE',
    tripStatus: 'W',
    tripType: 'P',
    tripZone: 99,
    updateByUser: 'REALTIME',
    updatedBy: 'realtime',
    vehicleType: 'K',
    yardNumber: 11,
    year: 2012,
    forms: {},
    status: 'assigned',
    issue: {},
  },
  {
    cashTag: '',
    chargesDue: '$100.00',
    clientUpdateTime: '2018-01-16T08: 08: 42Z',
    colors: 'BURN',
    damageCode: 'AO',
    description: '12 AUDI A3 BURN',
    destination: {
      accurate: true,
      city: 'HOUSTON',
      crossstreet: 'USA',
      exists: true,
      lat: 29.9685949,
      line1: '1655 RANKIN ROAD',
      line2: '',
      lng: -95.37359819999999,
      name: 'TX - HOUSTON',
      pano_id: 'YD4jHCnSbHoHpqDhw01sdA',
      partial_match: true,
      state: 'TX',
      zip: '77073',
      zpp: '',
    },
    destinationLocationId: 'yard-11',
    dispatch_status: 'A',
    isPartialTripLot: false,
    isTowable: 'Y',
    jobUpdateTime: '2018-01-16T00: 08: 40Z',
    lossType: 'C - COLLISION',
    lotStage: 28,
    lotTripId: 7243526023,
    make: 'AUDI',
    model: 'A3',
    number: 52406757,
    pickupNotes:
      'Make it totally clear that this gun has a right end and a wrong end. Make it totally clear to anyone standing at the wrong end that things are going badly for them. If that means sticking all sort of spikes and prongs and blackened bits all over it then so be it. This is not a gun for hanging over the fireplace or sticking in the umbrella stand, it is a gun for going out and making people miserable with.',
    pickupPhoneNumber: {
      areaCode: '508',
      extension: '',
      line: '6745570',
    },
    promisedTripDate: '2017-11-29',
    responsible_party_name: 'April Ludgate',
    tripId: 'SHPANDEY-1516090090524',
    scheduledTimeFrom: '',
    scheduledTimeTo: '',
    sellerNumber: 'FRR1',
    sellerReference: '',
    source: {
      availibility: {
        days: 'Mon-Fri',
        hours: '6am - 7pm',
      },
      accurate: true,
      city: 'FALL RIVER',
      crossstreet: 'US',
      exists: true,
      lat: 41.6867981,
      line1: '635 WARREN ST',
      line2: '',
      lng: -71.1482061,
      name: 'J & J AUTO REPAIR',
      pano_id: 'QnoyXTOgY_br8UpWcGZBUw',
      partial_match: false,
      residence: 'N',
      state: 'MA',
      zip: '02721',
      zpp: '',
      paymentTypesAccepted: {
        card: true,
        check: true,
        cash: true,
      },
    },
    sourceLocationId: 'loc-7243478970',
    subhaulerContact: {
      areaCode: '281',
      line: '5460394',
    },
    subhaulerUser: 'A & S TOW',
    suffix: 'Q',
    towType: 'Standard',
    trackupdatedBy: 'CALL FOR RELEASE',
    tripStatus: 'P',
    tripType: 'P',
    tripZone: 99,
    updateByUser: 'REALTIME',
    updatedBy: 'realtime',
    vehicleType: 'C',
    yardNumber: 11,
    year: 2012,
    forms: {},
    status: 'assigned',
    issue: {},
  },
  {
    cashTag: '',
    chargesDue: '$100.00',
    clientUpdateTime: '2018-01-15T20: 55: 09Z',
    colors: 'BLACK',
    damageCode: 'AO',
    description: '12 AUDI A4 BLACK',
    destination: {
      accurate: true,
      city: 'HOUSTON',
      crossstreet: 'USA',
      exists: true,
      lat: 29.9685949,
      line1: '1655 RANKIN ROAD',
      line2: '',
      lng: -95.37359819999999,
      name: 'TX - HOUSTON',
      pano_id: 'YD4jHCnSbHoHpqDhw01sdA',
      partial_match: true,
      state: 'TX',
      zip: '77073',
      zpp: '',
    },
    destinationLocationId: 'yard-11',
    dispatch_status: 'A',
    isPartialTripLot: false,
    isTowable: 'Y',
    jobUpdateTime: '2018-01-15T12: 55: 01Z',
    lossType: 'C - COLLISION',
    lotStage: 28,
    lotTripId: 7243796406,
    make: 'AUDI',
    model: 'A4',
    number: 52425097,
    pickupNotes:
      'It is a well known fact that those people who most want to rule people are, ipso facto, those least suited to do it. To summarize the summary: anyone who is capable of getting themselves made President should on no account be allowed to do the job.',
    pickupPhoneNumber: {
      areaCode: '915',
      extension: '',
      line: '8738481',
    },
    promisedTripDate: '2017-12-04',
    responsible_party_name: 'April Ludgate',
    tripId: 'SRGAJULA-1516049696931',
    scheduledTimeFrom: '',
    scheduledTimeTo: '',
    sellerNumber: 'JST1',
    sellerReference: '',
    source: {
      availibility: {
        days: 'Mon-Fri',
        hours: '6am - 7pm',
      },
      accurate: true,
      city: 'CANUTILLO',
      crossstreet: '',
      exists: true,
      lat: 31.9554328,
      line1: '1350 BAYSHORE',
      line2: '',
      lng: -106.5743724,
      name: 'RESIDENCE',
      pano_id: 'a0fDRspIYWGweneEs--isA',
      partial_match: true,
      residence: 'N',
      state: 'TX',
      zip: '79835',
      zpp: '',
      paymentTypesAccepted: {
        card: true,
        check: true,
        cash: true,
      },
    },
    sourceLocationId: 'loc-7243212068',
    subhaulerContact: {
      areaCode: '979',
      line: '3322345',
    },
    subhaulerUser: 'A & S TOW',
    suffix: 'Q',
    towType: 'Standard',
    trackupdatedBy: 'CALL FOR RELEASE',
    tripStatus: 'P',
    tripType: 'P',
    tripZone: 99,
    updateByUser: 'REALTIME',
    updatedBy: 'realtime',
    vehicleType: 'H',
    yardNumber: 11,
    year: 2012,
    forms: {},
    status: 'assigned',
    issue: {},
  },
  {
    cashTag: '',
    chargesDue: '$100.00',
    clientUpdateTime: '2018-01-15T16: 06: 29Z',
    colors: 'BLACK',
    damageCode: 'AO',
    description: '12 AUDI A4 BLACK',
    destination: {
      accurate: true,
      city: 'HOUSTON',
      crossstreet: 'USA',
      exists: true,
      lat: 29.9685949,
      line1: '1655 RANKIN ROAD',
      line2: '',
      lng: -95.37359819999999,
      name: 'TX - HOUSTON',
      pano_id: 'YD4jHCnSbHoHpqDhw01sdA',
      partial_match: true,
      state: 'TX',
      zip: '77073',
      zpp: '',
    },
    destinationLocationId: 'yard-11',
    dispatch_status: 'A',
    isPartialTripLot: false,
    isTowable: 'Y',
    jobUpdateTime: '2017-12-15T10: 04: 00Z',
    lossType: 'C - COLLISION',
    lotStage: 20,
    lotTripId: 7243796425,
    make: 'AUDI',
    model: 'A4',
    number: 52425117,
    pickupNotes:
      '“Since we decided a few weeks ago to adopt the leaf as legal tender, we have, of course, all become immensely rich.”',
    pickupPhoneNumber: {
      areaCode: '915',
      extension: '',
      line: '8738481',
    },
    promisedTripDate: '2017-12-04',
    responsible_party_name: 'April Ludgate',
    tripId: 'tenyima-1516032388834',
    scheduledTimeFrom: '',
    scheduledTimeTo: '',
    sellerNumber: 'JST1',
    sellerReference: '',
    source: {
      availibility: {
        days: 'Mon-Fri',
        hours: '6am - 7pm',
      },
      accurate: true,
      city: 'CANUTILLO',
      crossstreet: '',
      exists: true,
      lat: 31.9554328,
      line1: '1350 BAYSHORE',
      line2: '',
      lng: -106.5743724,
      name: 'RESIDENCE',
      pano_id: 'a0fDRspIYWGweneEs--isA',
      partial_match: true,
      residence: 'N',
      state: 'TX',
      zip: '79835',
      zpp: '',
      paymentTypesAccepted: {
        card: true,
        check: true,
        cash: true,
      },
    },
    sourceLocationId: 'loc-7243212068',
    subhaulerUser: 'A & S TOW',
    suffix: 'Q',
    towType: 'Standard',
    trackupdatedBy: 'CALL FOR RELEASE',
    tripStatus: 'W',
    tripType: 'P',
    tripZone: 99,
    updateByUser: 'OPSPORTAL-tenyima',
    updatedBy: 'realtime',
    vehicleType: 'R',
    yardNumber: 11,
    year: 2012,
    forms: {},
    status: 'assigned',
    issue: {},
  },
  {
    cashTag: '',
    chargesDue: '$100.00',
    clientUpdateTime: '2018-01-15T16: 06: 29Z',
    colors: 'BLACK',
    damageCode: 'AO',
    description: '12 AUDI A4 BLACK',
    destination: {
      accurate: true,
      city: 'HOUSTON',
      crossstreet: 'USA',
      exists: true,
      lat: 29.9685949,
      line1: '1655 RANKIN ROAD',
      line2: '',
      lng: -95.37359819999999,
      name: 'TX - HOUSTON',
      pano_id: 'YD4jHCnSbHoHpqDhw01sdA',
      partial_match: true,
      state: 'TX',
      zip: '77073',
      zpp: '',
    },
    destinationLocationId: 'yard-11',
    dispatch_status: 'A',
    isPartialTripLot: false,
    isTowable: 'Y',
    jobUpdateTime: '2017-12-15T11: 21: 54Z',
    lossType: 'C - COLLISION',
    lotStage: 20,
    lotTripId: 7243796437,
    make: 'AUDI',
    model: 'A4',
    number: 52425137,
    pickupNotes:
      'He gazed keenly into the distance and looked as if he would quite like the wind to blow his hair back dramatically at that point, but the wind was busy fooling around with some leaves a little way off.',
    pickupPhoneNumber: {
      areaCode: '915',
      extension: '',
      line: '8738481',
    },
    promisedTripDate: '2017-12-04',
    responsible_party_name: 'April Ludgate',
    tripId: 'tenyima-1516032388834',
    scheduledTimeFrom: '',
    scheduledTimeTo: '',
    sellerNumber: 'JST1',
    sellerReference: '',
    source: {
      accurate: true,
      city: 'CANUTILLO',
      crossstreet: '',
      exists: true,
      lat: 31.9554328,
      line1: '1350 BAYSHORE',
      line2: '',
      lng: -106.5743724,
      name: 'RESIDENCE',
      pano_id: 'a0fDRspIYWGweneEs--isA',
      partial_match: true,
      residence: 'N',
      state: 'TX',
      zip: '79835',
      zpp: '',
      paymentTypesAccepted: {
        card: true,
        check: true,
        cash: true,
      },
    },
    sourceLocationId: 'loc-7243212068',
    subhaulerUser: 'A & S TOW',
    suffix: 'Q',
    towType: 'Standard',
    trackupdatedBy: 'CALL FOR RELEASE',
    tripStatus: 'W',
    tripType: 'P',
    tripZone: 99,
    updateByUser: 'OPSPORTAL-tenyima',
    updatedBy: 'realtime',
    vehicleType: 'S',
    yardNumber: 11,
    year: 2012,
    forms: {},
    status: 'assigned',
    issue: {},
  },
  {
    cashTag: '',
    chargesDue: '$100.00',
    clientUpdateTime: '2018-01-15T16: 06: 29Z',
    colors: 'BLACK',
    damageCode: 'AO',
    description: '12 AUDI A4 BLACK',
    destination: {
      accurate: true,
      city: 'HOUSTON',
      crossstreet: 'USA',
      exists: true,
      lat: 29.9685949,
      line1: '1655 RANKIN ROAD',
      line2: '',
      lng: -95.37359819999999,
      name: 'TX - HOUSTON',
      pano_id: 'YD4jHCnSbHoHpqDhw01sdA',
      partial_match: true,
      state: 'TX',
      zip: '77073',
      zpp: '',
    },
    destinationLocationId: 'yard-11',
    dispatch_status: 'A',
    isPartialTripLot: false,
    isTowable: 'Y',
    jobUpdateTime: '2017-11-30T10: 27: 35Z',
    lossType: 'C - COLLISION',
    lotStage: 20,
    lotTripId: 7243796460,
    make: 'AUDI',
    model: 'A4',
    number: 52425167,
    pickupNotes:
      '“He was staring at the instruments with the air of one who is trying to convert Fahrenheit to centigrade in his head while his house is burning down.”',
    pickupPhoneNumber: {
      areaCode: '915',
      extension: '',
      line: '8738481',
    },
    promisedTripDate: '2017-12-04',
    responsible_party_name: 'April Ludgate',
    tripId: 'tenyima-1516032388834',
    scheduledTimeFrom: '',
    scheduledTimeTo: '',
    sellerNumber: 'JST1',
    sellerReference: '',
    source: {
      availibility: {
        days: 'Mon-Fri',
        hours: '6am - 7pm',
      },
      accurate: true,
      city: 'CANUTILLO',
      crossstreet: '',
      exists: true,
      lat: 31.9554328,
      line1: '1350 BAYSHORE',
      line2: '',
      lng: -106.5743724,
      name: 'RESIDENCE',
      pano_id: 'a0fDRspIYWGweneEs--isA',
      partial_match: true,
      residence: 'N',
      state: 'TX',
      zip: '79835',
      zpp: '',
      paymentTypesAccepted: {
        card: true,
        check: true,
        cash: true,
      },
    },
    sourceLocationId: 'loc-7243212068',
    subhaulerUser: 'A & S TOW',
    suffix: 'Q',
    towType: 'Standard',
    trackupdatedBy: 'CALL FOR RELEASE',
    tripStatus: 'W',
    tripType: 'P',
    tripZone: 99,
    updateByUser: 'OPSPORTAL-tenyima',
    updatedBy: 'realtime',
    vehicleType: 'L',
    yardNumber: 11,
    year: 2012,
    forms: {},
    status: 'assigned',
    issue: {},
  },
  {
    cashTag: '',
    chargesDue: '$100.00',
    clientUpdateTime: '2018-01-15T16: 06: 29Z',
    colors: 'BLACK',
    damageCode: 'AO',
    description: '12 KIA AMANTI BLACK',
    destination: {
      accurate: true,
      city: 'HOUSTON',
      crossstreet: 'USA',
      exists: true,
      lat: 29.9685949,
      line1: '1655 RANKIN ROAD',
      line2: '',
      lng: -95.37359819999999,
      name: 'TX - HOUSTON',
      pano_id: 'YD4jHCnSbHoHpqDhw01sdA',
      partial_match: true,
      state: 'TX',
      zip: '77073',
      zpp: '',
    },
    destinationLocationId: 'yard-11',
    dispatch_status: 'A',
    isPartialTripLot: false,
    isTowable: 'Y',
    jobUpdateTime: '2017-11-30T10: 50: 38Z',
    lossType: 'C - COLLISION',
    lotStage: 20,
    lotTripId: 7243796852,
    make: 'KIA',
    model: 'AMANTI',
    number: 52425457,
    pickupNotes:
      'There is a moment in every dawn when light floats, there is the possibility of magic. Creation holds its breath.',
    pickupPhoneNumber: {
      areaCode: '915',
      extension: '',
      line: '8738481',
    },
    promisedTripDate: '2017-12-04',
    responsible_party_name: 'April Ludgate',
    tripId: 'tenyima-1516032388834',
    scheduledTimeFrom: '',
    scheduledTimeTo: '',
    sellerNumber: 'SBU1',
    sellerReference: '',
    source: {
      availibility: {
        days: 'Mon-Fri',
        hours: '6am - 7pm',
      },
      accurate: true,
      city: 'CANUTILLO',
      crossstreet: '',
      exists: true,
      lat: 31.9554328,
      line1: '1350 BAYSHORE',
      line2: '',
      lng: -106.5743724,
      name: 'RESIDENCE',
      pano_id: 'a0fDRspIYWGweneEs--isA',
      partial_match: true,
      residence: 'N',
      state: 'TX',
      zip: '79835',
      zpp: '',
      paymentTypesAccepted: {
        card: true,
        check: true,
        cash: true,
      },
    },
    sourceLocationId: 'loc-7243212068',
    subhaulerUser: 'A & S TOW',
    suffix: 'Q',
    towType: 'Standard',
    trackupdatedBy: 'CALL FOR RELEASE',
    tripStatus: 'W',
    tripType: 'P',
    tripZone: 99,
    updateByUser: 'OPSPORTAL-tenyima',
    updatedBy: 'realtime',
    vehicleType: 'T',
    yardNumber: 11,
    year: 2012,
    forms: {},
    status: 'assigned',
    issue: {},
  },
  {
    cashTag: '',
    chargesDue: '$100.00',
    clientUpdateTime: '2018-01-15T16: 06: 30Z',
    colors: 'BLACK',
    damageCode: 'AO',
    description: '12 KIA AMANTI BLACK',
    destination: {
      accurate: true,
      city: 'HOUSTON',
      crossstreet: 'USA',
      exists: true,
      lat: 29.9685949,
      line1: '1655 RANKIN ROAD',
      line2: '',
      lng: -95.37359819999999,
      name: 'TX - HOUSTON',
      pano_id: 'YD4jHCnSbHoHpqDhw01sdA',
      partial_match: true,
      state: 'TX',
      zip: '77073',
      zpp: '',
    },
    destinationLocationId: 'yard-11',
    dispatch_status: 'A',
    isPartialTripLot: false,
    isTowable: 'Y',
    jobUpdateTime: '2017-11-30T10: 51: 37Z',
    lossType: 'C - COLLISION',
    lotStage: 20,
    lotTripId: 7243796864,
    make: 'KIA',
    model: 'AMANTI',
    number: 52425477,
    pickupNotes:
      'There is an art, it says, or rather, a knack to flying. The knack lies in learning how to throw yourself at the ground and miss.',
    pickupPhoneNumber: {
      areaCode: '915',
      extension: '',
      line: '8738481',
    },
    promisedTripDate: '2017-12-04',
    responsible_party_name: 'April Ludgate',
    tripId: 'tenyima-1516032388834',
    scheduledTimeFrom: '',
    scheduledTimeTo: '',
    sellerNumber: 'SBU1',
    sellerReference: '',
    source: {
      accurate: true,
      city: 'CANUTILLO',
      crossstreet: '',
      exists: true,
      lat: 31.9554328,
      line1: '1350 BAYSHORE',
      line2: '',
      lng: -106.5743724,
      name: 'RESIDENCE',
      pano_id: 'a0fDRspIYWGweneEs--isA',
      partial_match: true,
      residence: 'N',
      state: 'TX',
      zip: '79835',
      zpp: '',
      paymentTypesAccepted: {
        card: true,
        check: true,
        cash: true,
      },
    },
    sourceLocationId: 'loc-7243212068',
    subhaulerUser: 'A & S TOW',
    suffix: 'Q',
    towType: 'Standard',
    trackupdatedBy: 'CALL FOR RELEASE',
    tripStatus: 'W',
    tripType: 'P',
    tripZone: 99,
    updateByUser: 'OPSPORTAL-tenyima',
    updatedBy: 'realtime',
    vehicleType: 'V - AUTOMOBILE',
    yardNumber: 11,
    year: 2012,
    forms: {},
    status: 'assigned',
    issue: {},
  },
  {
    cashTag: '',
    chargesDue: '$100.00',
    clientUpdateTime: '2018-01-15T10: 43: 32Z',
    colors: 'BLACK',
    damageCode: 'AO',
    description: '12 KIA AMANTI BLACK',
    destination: {
      accurate: true,
      city: 'HOUSTON',
      crossstreet: 'USA',
      exists: true,
      lat: 29.9685949,
      line1: '1655 RANKIN ROAD',
      line2: '',
      lng: -95.37359819999999,
      name: 'TX - HOUSTON',
      pano_id: 'YD4jHCnSbHoHpqDhw01sdA',
      partial_match: true,
      state: 'TX',
      zip: '77073',
      zpp: '',
    },
    destinationLocationId: 'yard-11',
    dispatch_status: 'A',
    isPartialTripLot: false,
    isTowable: 'Y',
    jobUpdateTime: '2018-01-15T01: 36: 49Z',
    lossType: 'C - COLLISION',
    lotStage: 28,
    lotTripId: 7243796942,
    make: 'KIA',
    model: 'AMANTI',
    number: 52425727,
    pickupNotes:
      'He hoped and prayed that there wasn’t an afterlife. Then he realized there was a contradiction involved here and merely hoped that there wasn’t an afterlife.',
    pickupPhoneNumber: {
      areaCode: '915',
      extension: '',
      line: '8738481',
    },
    promisedTripDate: '2017-12-04',
    responsible_party_name: 'April Ludgate',
    tripId: 'sxparia-1516008997269',
    scheduledTimeFrom: '',
    scheduledTimeTo: '',
    sellerNumber: 'SBU1',
    sellerReference: '',
    source: {
      availibility: { days: 'Mon-Fri', hours: '6am - 7pm' },
      accurate: true,
      city: 'CANUTILLO',
      crossstreet: '',
      exists: true,
      lat: 31.9554328,
      line1: '1350 BAYSHORE',
      line2: '',
      lng: -106.5743724,
      name: 'RESIDENCE',
      pano_id: 'a0fDRspIYWGweneEs--isA',
      partial_match: true,
      residence: 'N',
      state: 'TX',
      zip: '79835',
      zpp: '',
      paymentTypesAccepted: {
        card: true,
        check: true,
        cash: true,
      },
    },
    sourceLocationId: 'loc-7243212068',
    subhaulerContact: {
      areaCode: '361',
      line: '8537323',
    },
    subhaulerUser: 'A & S TOW',
    suffix: 'Q',
    towType: 'Standard',
    trackupdatedBy: 'CALL FOR RELEASE',
    tripStatus: 'P',
    tripType: 'P',
    tripZone: 99,
    updateByUser: 'REALTIME',
    updatedBy: 'realtime',
    vehicleType: 'V - AUTOMOBILE',
    yardNumber: 11,
    year: 2012,
    forms: {},
    status: 'assigned',
    issue: {},
  },
  {
    cashTag: '',
    chargesDue: '$100.00',
    clientUpdateTime: '2018-01-16T12: 42: 41Z',
    colors: 'BLACK',
    damageCode: 'AO',
    description: '12 KIA AMANTI BLACK',
    destination: {
      accurate: true,
      city: 'HOUSTON',
      crossstreet: 'USA',
      exists: true,
      lat: 29.9685949,
      line1: '1655 RANKIN ROAD',
      line2: '',
      lng: -95.37359819999999,
      name: 'TX - HOUSTON',
      pano_id: 'YD4jHCnSbHoHpqDhw01sdA',
      partial_match: true,
      state: 'TX',
      zip: '77073',
      zpp: '',
    },
    destinationLocationId: 'yard-11',
    dispatch_status: 'A',
    isPartialTripLot: false,
    isTowable: 'Y',
    jobUpdateTime: '2018-01-16T04: 42: 30Z',
    lossType: 'C - COLLISION',
    lotStage: 28,
    lotTripId: 7243797027,
    make: 'KIA',
    model: 'AMANTI',
    number: 52425827,
    pickupNotes:
      'The storm had now definitely abated, and what thunder there was now grumbled over more distant hills, like a man saying “And another thing…” twenty minutes after admitting he’s lost the argument.',
    pickupPhoneNumber: {
      areaCode: '915',
      extension: '',
      line: '8738481',
    },
    promisedTripDate: '2017-12-04',
    responsible_party_name: 'April Ludgate',
    tripId: 'CXGANDLA-1516106548183',
    scheduledTimeFrom: '',
    scheduledTimeTo: '',
    sellerNumber: 'SBU1',
    sellerReference: '',
    source: {
      availibility: { days: 'Mon-Fri', hours: '6am - 7pm' },
      accurate: true,
      city: 'CANUTILLO',
      crossstreet: '',
      exists: true,
      lat: 31.9554328,
      line1: '1350 BAYSHORE',
      line2: '',
      lng: -106.5743724,
      name: 'RESIDENCE',
      pano_id: 'a0fDRspIYWGweneEs--isA',
      partial_match: true,
      residence: 'N',
      state: 'TX',
      zip: '79835',
      zpp: '',
      paymentTypesAccepted: {
        card: true,
        check: true,
        cash: true,
      },
    },
    sourceLocationId: 'loc-7243212068',
    subhaulerContact: {
      areaCode: '979',
      line: '3322345',
    },
    subhaulerUser: 'A & S TOW',
    suffix: 'Q',
    towType: 'Standard',
    trackupdatedBy: 'CALL FOR RELEASE',
    tripStatus: 'P',
    tripType: 'P',
    tripZone: 99,
    updateByUser: 'REALTIME',
    updatedBy: 'realtime',
    vehicleType: 'V - AUTOMOBILE',
    yardNumber: 11,
    year: 2012,
    forms: {},
    status: 'assigned',
    issue: {},
  },
  {
    cashTag: '',
    chargesDue: '$100.00',
    clientUpdateTime: '2018-01-16T12: 42: 43Z',
    colors: 'BLACK',
    damageCode: 'AO',
    description: '12 KIA AMANTI BLACK',
    destination: {
      accurate: true,
      city: 'HOUSTON',
      crossstreet: 'USA',
      exists: true,
      lat: 29.9685949,
      line1: '1655 RANKIN ROAD',
      line2: '',
      lng: -95.37359819999999,
      name: 'TX - HOUSTON',
      pano_id: 'YD4jHCnSbHoHpqDhw01sdA',
      partial_match: true,
      state: 'TX',
      zip: '77073',
      zpp: '',
    },
    destinationLocationId: 'yard-11',
    dispatch_status: 'A',
    isPartialTripLot: false,
    isTowable: 'Y',
    jobUpdateTime: '2018-01-16T04: 42: 31Z',
    lossType: 'C - COLLISION',
    lotStage: 28,
    lotTripId: 7243797073,
    make: 'KIA',
    model: 'AMANTI',
    number: 52425877,
    pickupNotes:
      '“Nothing travels faster than the speed of light with the possible exception of bad news, which obeys its own special laws.”',
    pickupPhoneNumber: {
      areaCode: '915',
      extension: '',
      line: '8738481',
    },
    promisedTripDate: '2017-12-04',
    responsible_party_name: 'April Ludgate',
    tripId: 'CXGANDLA-1516106548183',
    scheduledTimeFrom: '',
    scheduledTimeTo: '',
    sellerNumber: 'SBU1',
    sellerReference: '',
    source: {
      availibility: { days: 'Mon-Fri', hours: '6am - 7pm' },
      accurate: true,
      city: 'CANUTILLO',
      crossstreet: '',
      exists: true,
      lat: 31.9554328,
      line1: '1350 BAYSHORE',
      line2: '',
      lng: -106.5743724,
      name: 'RESIDENCE',
      pano_id: 'a0fDRspIYWGweneEs--isA',
      partial_match: true,
      residence: 'N',
      state: 'TX',
      zip: '79835',
      zpp: '',
      paymentTypesAccepted: {
        card: true,
        check: true,
        cash: true,
      },
    },
    sourceLocationId: 'loc-7243212068',
    subhaulerContact: {
      areaCode: '979',
      line: '3322345',
    },
    subhaulerUser: 'A & S TOW',
    suffix: 'Q',
    towType: 'Standard',
    trackupdatedBy: 'CALL FOR RELEASE',
    tripStatus: 'P',
    tripType: 'P',
    tripZone: 99,
    updateByUser: 'REALTIME',
    updatedBy: 'realtime',
    vehicleType: 'V - AUTOMOBILE',
    yardNumber: 11,
    year: 2012,
    forms: {},
    status: 'assigned',
    issue: {},
  },
  {
    cashTag: '',
    chargesDue: '$100.00',
    clientUpdateTime: '2018-01-15T21: 22: 12Z',
    colors: 'BURN',
    damageCode: 'AO',
    description: '13 HOND ACCORD BURN',
    destination: {
      accurate: true,
      city: 'HOUSTON',
      crossstreet: 'USA',
      exists: true,
      lat: 29.9685949,
      line1: '1655 RANKIN ROAD',
      line2: '',
      lng: -95.37359819999999,
      name: 'TX - HOUSTON',
      pano_id: 'YD4jHCnSbHoHpqDhw01sdA',
      partial_match: true,
      state: 'TX',
      zip: '77073',
      zpp: '',
    },
    destinationLocationId: 'yard-11',
    dispatch_status: 'A',
    isPartialTripLot: false,
    isTowable: 'Y',
    jobUpdateTime: '2018-01-15T13: 20: 50Z',
    lossType: 'C - COLLISION',
    lotStage: 28,
    lotTripId: 7244750312,
    make: 'HOND',
    model: 'ACCORD',
    number: 52641928,
    pickupNotes:
      'The last time anybody made a list of the top hundred character attributes of New Yorkers, common sense snuck in at number 79.',
    pickupPhoneNumber: {
      areaCode: '214',
      extension: '',
      line: '4933627',
    },
    promisedTripDate: '2018-01-15',
    responsible_party_name: 'April Ludgate',
    tripId: 'sanataraja-1516051241576',
    scheduledTimeFrom: '',
    scheduledTimeTo: '',
    sellerNumber: 'JST1',
    sellerReference: '',
    source: {
      availibility: { days: 'Mon-Fri', hours: '6am - 7pm' },
      accurate: true,
      city: 'HOUSTON',
      crossstreet: '',
      exists: false,
      lat: 29.6728934,
      line1: '9802 FORUM PARK DR',
      line2: '',
      lng: -95.5558368,
      name: 'HOUSTON',
      partial_match: false,
      residence: 'N',
      state: 'TX',
      zip: '77036',
      zpp: '',
      paymentTypesAccepted: {
        card: true,
        check: true,
        cash: true,
      },
    },
    sourceLocationId: 'loc-4784678750',
    subhaulerContact: {
      areaCode: '979',
      line: '3322345',
    },
    subhaulerUser: 'A & S TOW',
    suffix: 'Q',
    towType: 'Standard',
    trackupdatedBy: 'CALL FOR RELEASE',
    tripStatus: 'P',
    tripType: 'P',
    tripZone: 5,
    updateByUser: 'REALTIME',
    updatedBy: 'realtime',
    vehicleType: 'V - AUTOMOBILE',
    yardNumber: 11,
    year: 2013,
    forms: {},
    status: 'assigned',
    issue: {},
  },
  {
    cashTag: '',
    chargesDue: '$100.00',
    clientUpdateTime: '2018-01-15T21: 22: 02Z',
    colors: 'BURN',
    damageCode: 'AO',
    description: '17 AUDI A3 BURN',
    destination: {
      accurate: true,
      city: 'HOUSTON',
      crossstreet: 'USA',
      exists: true,
      lat: 29.9685949,
      line1: '1655 RANKIN ROAD',
      line2: '',
      lng: -95.37359819999999,
      name: 'TX - HOUSTON',
      pano_id: 'YD4jHCnSbHoHpqDhw01sdA',
      partial_match: true,
      state: 'TX',
      zip: '77073',
      zpp: '',
    },
    destinationLocationId: 'yard-11',
    dispatch_status: 'A',
    isPartialTripLot: false,
    isTowable: 'Y',
    jobUpdateTime: '2018-01-15T13: 20: 49Z',
    lossType: 'C - COLLISION',
    lotStage: 28,
    lotTripId: 7244756942,
    make: 'AUDI',
    model: 'A3',
    number: 52643258,
    pickupNotes:
      'All you really need to know for the moment is that the universe is a lot more complicated than you might think, even if you start from a position of thinking it’s pretty damn complicated in the first place.',
    pickupPhoneNumber: {
      areaCode: '713',
      extension: '',
      line: '7767985',
    },
    promisedTripDate: '2018-01-16',
    responsible_party_name: 'April Ludgate',
    tripId: 'sanataraja-1516051241576',
    scheduledTimeFrom: '',
    scheduledTimeTo: '',
    sellerNumber: 'FRR1',
    sellerReference: '',
    source: {
      availibility: { days: 'Mon-Fri', hours: '6am - 7pm' },
      accurate: true,
      city: 'HOUSTON',
      crossstreet: 'US',
      exists: true,
      lat: 29.6650977,
      line1: '10565 W SAM HOUSTON PKWY S',
      line2: '',
      lng: -95.557282,
      name: '$4500.00 - GILLMAN COLL CENTER',
      pano_id: 'CAoSLEFGMVFpcFBRak9iVTBvTmY1NFljZzlqc0ctUjFCYzEteXRsdENXZ0MtejFY',
      partial_match: false,
      residence: 'N',
      state: 'TX',
      zip: '77036',
      zpp: '',
      paymentTypesAccepted: {
        card: true,
        check: true,
        cash: true,
      },
    },
    sourceLocationId: 'loc-7244239710',
    subhaulerContact: {
      areaCode: '979',
      line: '3322345',
    },
    subhaulerUser: 'A & S TOW',
    suffix: 'Q',
    towType: 'Standard',
    trackupdatedBy: 'CALL FOR RELEASE',
    tripStatus: 'P',
    tripType: 'P',
    tripZone: 5,
    updateByUser: 'REALTIME',
    updatedBy: 'realtime',
    vehicleType: 'V - AUTOMOBILE',
    yardNumber: 11,
    year: 2017,
    forms: {},
    status: 'assigned',
    issue: {},
  },
  {
    cashTag: '',
    chargesDue: '$100.00',
    clientUpdateTime: '2018-01-15T21: 21: 52Z',
    colors: 'BEIGE',
    damageCode: 'AO',
    description: '13 HOND ACCORD BEIGE',
    destination: {
      accurate: true,
      city: 'HOUSTON',
      crossstreet: 'USA',
      exists: true,
      lat: 29.9685949,
      line1: '1655 RANKIN ROAD',
      line2: '',
      lng: -95.37359819999999,
      name: 'TX - HOUSTON',
      pano_id: 'YD4jHCnSbHoHpqDhw01sdA',
      partial_match: true,
      state: 'TX',
      zip: '77073',
      zpp: '',
    },
    destinationLocationId: 'yard-11',
    dispatch_status: 'A',
    isPartialTripLot: false,
    isTowable: 'Y',
    jobUpdateTime: '2018-01-15T13: 20: 49Z',
    lossType: 'C - COLLISION',
    lotStage: 28,
    lotTripId: 7244757089,
    make: 'HOND',
    model: 'ACCORD',
    number: 52643468,
    pickupNotes: 'The ships hung in the sky in much the same way that bricks don’t.',
    pickupPhoneNumber: {
      areaCode: '214',
      extension: '',
      line: '4933627',
    },
    promisedTripDate: '2018-01-12',
    responsible_party_name: 'April Ludgate',
    tripId: 'sanataraja-1516051241576',
    scheduledTimeFrom: '',
    scheduledTimeTo: '',
    sellerNumber: 'JST1',
    sellerReference: '',
    source: {
      availibility: { days: 'Mon-Fri', hours: '6am - 7pm' },
      accurate: true,
      city: 'HOUSTON',
      crossstreet: '',
      exists: false,
      lat: 29.6728934,
      line1: '9802 FORUM PARK DR',
      line2: '',
      lng: -95.5558368,
      name: 'HOUSTON',
      partial_match: false,
      residence: 'N',
      state: 'TX',
      zip: '77036',
      zpp: '',
      paymentTypesAccepted: {
        card: true,
        check: true,
        cash: true,
      },
    },
    sourceLocationId: 'loc-4784678750',
    subhaulerContact: {
      areaCode: '979',
      line: '3322345',
    },
    subhaulerUser: 'A & S TOW',
    suffix: 'Q',
    towType: 'Standard',
    trackupdatedBy: 'CALL FOR RELEASE',
    tripStatus: 'P',
    tripType: 'P',
    tripZone: 5,
    updateByUser: 'REALTIME',
    updatedBy: 'realtime',
    vehicleType: 'V - AUTOMOBILE',
    yardNumber: 11,
    year: 2013,
    forms: {},
    status: 'assigned',
    issue: {},
  },
  {
    cashTag: '',
    chargesDue: '$100.00',
    clientUpdateTime: '2018-01-15T21: 21: 43Z',
    colors: 'BURN',
    damageCode: 'AO',
    description: '03 HOND ACCORD BURN',
    destination: {
      accurate: true,
      city: 'HOUSTON',
      crossstreet: 'USA',
      exists: true,
      lat: 29.9685949,
      line1: '1655 RANKIN ROAD',
      line2: '',
      lng: -95.37359819999999,
      name: 'TX - HOUSTON',
      pano_id: 'YD4jHCnSbHoHpqDhw01sdA',
      partial_match: true,
      state: 'TX',
      zip: '77073',
      zpp: '',
    },
    destinationLocationId: 'yard-11',
    dispatch_status: 'A',
    isPartialTripLot: false,
    isTowable: 'Y',
    jobUpdateTime: '2018-01-15T13: 20: 46Z',
    lossType: 'C - COLLISION',
    lotStage: 28,
    lotTripId: 7244757119,
    make: 'HOND',
    model: 'ACCORD',
    number: 52643488,
    pickupNotes: 'Don\'t Panic',
    pickupPhoneNumber: {
      areaCode: '214',
      extension: '',
      line: '4933627',
    },
    promisedTripDate: '2018-01-12',
    responsible_party_name: 'April Ludgate',
    tripId: 'sanataraja-1516051241576',
    scheduledTimeFrom: '',
    scheduledTimeTo: '',
    sellerNumber: 'JST1',
    sellerReference: '',
    source: {
      availibility: { days: 'Mon-Fri', hours: '6am - 7pm' },
      accurate: true,
      city: 'HOUSTON',
      crossstreet: '',
      exists: false,
      lat: 29.6728934,
      line1: '9802 FORUM PARK DR',
      line2: '',
      lng: -95.5558368,
      name: 'HOUSTON',
      partial_match: false,
      residence: 'N',
      state: 'TX',
      zip: '77036',
      zpp: '',
      paymentTypesAccepted: {
        card: true,
        check: true,
        cash: true,
      },
    },
    sourceLocationId: 'loc-4784678750',
    subhaulerContact: {
      areaCode: '979',
      line: '3322345',
    },
    subhaulerUser: 'A & S TOW',
    suffix: 'Q',
    towType: 'Standard',
    trackupdatedBy: 'CALL FOR RELEASE',
    tripStatus: 'P',
    tripType: 'P',
    tripZone: 5,
    updateByUser: 'REALTIME',
    updatedBy: 'realtime',
    vehicleType: 'V - AUTOMOBILE',
    yardNumber: 11,
    year: 2003,
    forms: {},
    status: 'assigned',
    issue: {},
  },
  {
    cashTag: '',
    chargesDue: '$100.00',
    clientUpdateTime: '2018-01-15T13: 28: 07Z',
    colors: 'SILVR',
    damageCode: 'UK',
    description: '08 NISS SENTRA 2.0 SILVR',
    destination: {
      accurate: true,
      city: 'HOUSTON',
      crossstreet: 'USA',
      exists: true,
      lat: 29.9685949,
      line1: '1655 RANKIN ROAD',
      line2: '',
      lng: -95.37359819999999,
      name: 'TX - HOUSTON',
      pano_id: 'YD4jHCnSbHoHpqDhw01sdA',
      partial_match: true,
      state: 'TX',
      zip: '77073',
      zpp: '',
    },
    destinationLocationId: 'yard-11',
    dispatch_status: 'A',
    isPartialTripLot: false,
    isTowable: 'Y',
    jobUpdateTime: '2018-01-12T13: 27: 39Z',
    lossType: 'C - COLLISION',
    lotStage: 20,
    lotTripId: 7244829134,
    make: 'NISS',
    model: 'SENTRA 2.0',
    number: 52775428,
    pickupNotes: '“Life,” said Marvin dolefully, “loathe it or ignore it, you can’t like it.”',
    pickupPhoneNumber: {
      areaCode: '832',
      extension: '',
      line: '3842561',
    },
    promisedTripDate: '2018-01-16',
    responsible_party_name: 'April Ludgate',
    tripId: 'SXPARIA-1516022886427',
    scheduledTimeFrom: '',
    scheduledTimeTo: '',
    sellerNumber: 'F182',
    sellerReference: '',
    source: {
      availibility: { days: 'Mon-Fri', hours: '6am - 7pm' },
      accurate: true,
      city: 'HOUSTON',
      crossstreet: '',
      exists: true,
      lat: 29.6860158,
      line1: '13426 SANDERFORD LANE',
      line2: '',
      lng: -95.61706029999999,
      name: 'AA AFFORDABLE AUTO',
      pano_id: 'lxLl9ZsW9BD1-hNbBzs-Sg',
      partial_match: true,
      residence: 'N',
      state: 'TX',
      zip: '77083',
      zpp: '',
      paymentTypesAccepted: {
        card: true,
        check: true,
        cash: true,
      },
    },
    sourceLocationId: 'loc-1927877366',
    subhaulerUser: 'A & S TOW',
    suffix: 'X',
    towType: 'Standard',
    trackupdatedBy: 'CALL FOR RELEASE',
    tripStatus: 'W',
    tripType: 'P',
    tripZone: 7,
    updateByUser: 'OPSPORTAL-SXPARIA',
    updatedBy: 'realtime',
    vehicleType: 'V - AUTOMOBILE',
    yardNumber: 11,
    year: 2008,
    forms: {},
    status: 'assigned',
    issue: {},
  },
  {
    cashTag: '',
    chargesDue: '$100.00',
    clientUpdateTime: '2018-01-15T13: 28: 07Z',
    colors: 'SILVR',
    damageCode: 'UK',
    description: '15 CHEV MALIBU 1LT SILVR',
    destination: {
      accurate: true,
      city: 'HOUSTON',
      crossstreet: 'USA',
      exists: true,
      lat: 29.9685949,
      line1: '1655 RANKIN ROAD',
      line2: '',
      lng: -95.37359819999999,
      name: 'TX - HOUSTON',
      pano_id: 'YD4jHCnSbHoHpqDhw01sdA',
      partial_match: true,
      state: 'TX',
      zip: '77073',
      zpp: '',
    },
    destinationLocationId: 'yard-11',
    dispatch_status: 'A',
    isPartialTripLot: false,
    isTowable: 'Y',
    jobUpdateTime: '2018-01-12T13: 28: 04Z',
    lossType: 'C - COLLISION',
    lotStage: 20,
    lotTripId: 7244829136,
    make: 'CHEV',
    model: 'MALIBU 1LT',
    number: 52775438,
    pickupNotes:
      'The last ever dolphin message was misinterpreted as a surprisingly sophisticated attempt to do a double-backwards-somersault through a hoop whilst whistling the \'Star Spangled Banner\', but in fact the message was this: So long and thanks for all the fish.',
    pickupPhoneNumber: {
      areaCode: '832',
      extension: '',
      line: '3842561',
    },
    promisedTripDate: '2018-01-16',
    responsible_party_name: 'April Ludgate',
    tripId: 'SXPARIA-1516022886427',
    scheduledTimeFrom: '',
    scheduledTimeTo: '',
    sellerNumber: 'F182',
    sellerReference: '',
    source: {
      availibility: { days: 'Mon-Fri', hours: '6am - 7pm' },
      accurate: true,
      city: 'HOUSTON',
      crossstreet: '',
      exists: true,
      lat: 29.6860158,
      line1: '13426 SANDERFORD LANE',
      line2: '',
      lng: -95.61706029999999,
      name: 'AA AFFORDABLE AUTO',
      pano_id: 'lxLl9ZsW9BD1-hNbBzs-Sg',
      partial_match: true,
      residence: 'N',
      state: 'TX',
      zip: '77083',
      zpp: '',
      paymentTypesAccepted: {
        card: true,
        check: true,
        cash: true,
      },
    },
    sourceLocationId: 'loc-1927877366',
    subhaulerUser: 'A & S TOW',
    suffix: 'X',
    towType: 'Standard',
    trackupdatedBy: 'CALL FOR RELEASE',
    tripStatus: 'W',
    tripType: 'P',
    tripZone: 7,
    updateByUser: 'OPSPORTAL-SXPARIA',
    updatedBy: 'realtime',
    vehicleType: 'V - AUTOMOBILE',
    yardNumber: 11,
    year: 2015,
    forms: {},
    status: 'assigned',
    issue: {},
  },
  {
    cashTag: '',
    chargesDue: '$100.00',
    clientUpdateTime: '2018-01-15T13: 28: 07Z',
    colors: 'SILVR',
    damageCode: 'UK',
    description: '01 CHEV SILVERADO SILVR',
    destination: {
      accurate: true,
      city: 'HOUSTON',
      crossstreet: 'USA',
      exists: true,
      lat: 29.9685949,
      line1: '1655 RANKIN ROAD',
      line2: '',
      lng: -95.37359819999999,
      name: 'TX - HOUSTON',
      pano_id: 'YD4jHCnSbHoHpqDhw01sdA',
      partial_match: true,
      state: 'TX',
      zip: '77073',
      zpp: '',
    },
    destinationLocationId: 'yard-11',
    dispatch_status: 'A',
    isPartialTripLot: false,
    isTowable: 'Y',
    jobUpdateTime: '2018-01-14T04: 40: 20Z',
    lossType: 'C - COLLISION',
    lotStage: 20,
    lotTripId: 7244850203,
    make: 'CHEV',
    model: 'SILVERADO',
    number: 52776478,
    pickupNotes:
      'The bird that would soar above the plain of tradition and prejudice must have strong wings.',
    pickupPhoneNumber: {
      areaCode: '832',
      extension: '',
      line: '3842561',
    },
    promisedTripDate: '2018-01-16',
    responsible_party_name: 'April Ludgate',
    tripId: 'SXPARIA-1516022886427',
    scheduledTimeFrom: '',
    scheduledTimeTo: '',
    sellerNumber: 'F182',
    sellerReference: '',
    source: {
      availibility: { days: 'Mon-Fri', hours: '6am - 7pm' },
      accurate: true,
      city: 'HOUSTON',
      crossstreet: '',
      exists: true,
      lat: 29.6860158,
      line1: '13426 SANDERFORD LANE',
      line2: '',
      lng: -95.61706029999999,
      name: 'AA AFFORDABLE AUTO',
      pano_id: 'lxLl9ZsW9BD1-hNbBzs-Sg',
      partial_match: true,
      residence: 'N',
      state: 'TX',
      zip: '77083',
      zpp: '',
      paymentTypesAccepted: {
        card: true,
        check: true,
        cash: true,
      },
    },
    sourceLocationId: 'loc-1927877366',
    subhaulerUser: 'A & S TOW',
    suffix: 'X',
    towType: 'Standard',
    trackupdatedBy: 'CALL FOR RELEASE',
    tripStatus: 'W',
    tripType: 'P',
    tripZone: 7,
    updateByUser: 'OPSPORTAL-SXPARIA',
    updatedBy: 'realtime',
    vehicleType: 'V - AUTOMOBILE',
    yardNumber: 11,
    year: 2001,
    forms: {},
    status: 'assigned',
    issue: {},
  },
  {
    cashTag: '',
    chargesDue: '$100.00',
    clientUpdateTime: '2018-01-15T13: 24: 31Z',
    colors: 'SILVR',
    damageCode: 'UK',
    description: '10 HOND ACCORD EX SILVR',
    destination: {
      accurate: true,
      city: 'HOUSTON',
      crossstreet: 'USA',
      exists: true,
      lat: 29.9685949,
      line1: '1655 RANKIN ROAD',
      line2: '',
      lng: -95.37359819999999,
      name: 'TX - HOUSTON',
      pano_id: 'YD4jHCnSbHoHpqDhw01sdA',
      partial_match: true,
      state: 'TX',
      zip: '77073',
      zpp: '',
    },
    destinationLocationId: 'yard-11',
    dispatch_status: 'A',
    isPartialTripLot: false,
    isTowable: 'Y',
    jobUpdateTime: '2018-01-14T12: 40: 22Z',
    lossType: 'C - COLLISION',
    lotStage: 20,
    lotTripId: 7244850685,
    make: 'HOND',
    model: 'ACCORD EX',
    number: 52776928,
    pickupNotes:
      'Vogon poetry is of course, the third worst in the universe. The second worst is that of the Azgoths of Kria. During a recitation by their poet master Grunthos the Flatulent of his poem "Ode to a Small Lump of Green Putty I Found in My Armpit One Midsummer Morning" four of his audience died of internal haemorrhaging and the president of the Mid-Galactic Arts Nobbling Council survived by gnawing one of his own legs off. Grunthos was reported to have been "disappointed" by the poem\'s reception, and was about to embark on a reading of his 12-book epic entitled "My Favourite Bathtime Gurgles" when his own major intestine, in a desperate attempt to save humanity, leapt straight up through his neck and throttled his brain. The very worst poetry of all perished along with its creator, Paul Neil Milne Johnstone of Redbridge, in the destruction of the planet Earth. Vogon poetry is mild by comparison.',
    pickupPhoneNumber: {
      areaCode: '832',
      extension: '',
      line: '3842561',
    },
    promisedTripDate: '2018-01-16',
    responsible_party_name: 'April Ludgate',
    tripId: 'SXPARIA-1516022671197',
    scheduledTimeFrom: '',
    scheduledTimeTo: '',
    sellerNumber: 'F182',
    sellerReference: '',
    source: {
      accurate: true,
      city: 'HOUSTON',
      crossstreet: '',
      exists: true,
      lat: 29.6860158,
      line1: '13426 SANDERFORD LANE',
      line2: '',
      lng: -95.61706029999999,
      name: 'AA AFFORDABLE AUTO',
      pano_id: 'lxLl9ZsW9BD1-hNbBzs-Sg',
      partial_match: true,
      residence: 'N',
      state: 'TX',
      zip: '77083',
      zpp: '',
      paymentTypesAccepted: {
        card: true,
        check: true,
        cash: true,
      },
    },
    sourceLocationId: 'loc-1927877366',
    subhaulerUser: 'A & S TOW',
    suffix: 'X',
    towType: 'Standard',
    trackupdatedBy: 'CALL FOR RELEASE',
    tripStatus: 'W',
    tripType: 'P',
    tripZone: 7,
    updateByUser: 'OPSPORTAL-SXPARIA',
    updatedBy: 'realtime',
    vehicleType: 'V - AUTOMOBILE',
    yardNumber: 11,
    year: 2010,
    forms: {},
    status: 'assigned',
    issue: {},
  },
  {
    cashTag: '',
    chargesDue: '$100.00',
    clientUpdateTime: '2018-01-16T09: 37: 38Z',
    colors: 'RED',
    damageCode: 'AO',
    description: '05 HOND ACCORD RED',
    destination: {
      accurate: true,
      city: 'HOUSTON',
      crossstreet: '',
      exists: true,
      lat: 29.6698025,
      line1: '10000 SOUTHWEST FWY',
      line2: '',
      lng: -95.5516918,
      name: '$10000  MOMENTUM BMW',
      pano_id: 'h1exguGdFJahu7H-qh9vdw',
      partial_match: true,
      state: 'TX',
      zip: '77074',
      zpp: '',
    },
    destinationLocationId: 'loc-7240568139',
    dispatch_status: 'A',
    isPartialTripLot: false,
    isTowable: 'Y',
    jobUpdateTime: '2018-01-16T01: 11: 04Z',
    lossType: 'C - COLLISION',
    lotStage: 28,
    lotTripId: 7244867787,
    make: 'HOND',
    model: 'ACCORD',
    number: 52780298,
    pickupNotes:
      'Ford carried on counting quietly. This is about the most aggressive thing you can do to a computer, the equivalent of going up to a human being and saying "Blood...blood...blood...blood..."',
    pickupPhoneNumber: {
      areaCode: '817',
      extension: '',
      line: '5942804',
    },
    promisedTripDate: '2018-01-17',
    responsible_party_name: 'April Ludgate',
    tripId: 'sxparia-1516093861213',
    scheduledTimeFrom: '',
    scheduledTimeTo: '',
    sellerNumber: 'EAU9',
    sellerReference: '',
    source: {
      accurate: false,
      city: 'WEATHERFORD',
      crossstreet: '',
      exists: false,
      lat: 32.7563427,
      line1: '2602 FORT WORTH HWY',
      line2: '',
      lng: -97.7188577,
      name: 'LESSIGS TOWING',
      partial_match: true,
      residence: 'N',
      state: 'TX',
      zip: '76087',
      zpp: '',
      paymentTypesAccepted: {
        cash: true,
        card: true,
        check: true,
      },
    },
    sourceLocationId: 'loc-1112650',
    subhaulerContact: {
      areaCode: '361',
      line: '8537323',
    },
    subhaulerUser: 'A & S TOW',
    suffix: 'T',
    towType: 'Standard',
    trackupdatedBy: 'CALL FOR RELEASE',
    tripStatus: 'P',
    tripType: 'T',
    tripZone: 51,
    updateByUser: 'REALTIME',
    updatedBy: 'realtime',
    vehicleType: 'T - TRANSPORT',
    yardNumber: 11,
    year: 2005,
    forms: {},
    status: 'assigned',
    issue: {},
  },
  {
    cashTag: '',
    chargesDue: '$100.00',
    clientUpdateTime: '2018-01-16T11: 37: 21Z',
    colors: 'RED',
    damageCode: 'AO',
    description: '05 HOND ACCORD RED',
    destination: {
      accurate: true,
      city: 'HOUSTON',
      crossstreet: 'USA',
      exists: true,
      lat: 29.9685949,
      line1: '1655 RANKIN ROAD',
      line2: '',
      lng: -95.37359819999999,
      name: 'TX - HOUSTON',
      pano_id: 'YD4jHCnSbHoHpqDhw01sdA',
      partial_match: true,
      state: 'TX',
      zip: '77073',
      zpp: '',
    },
    destinationLocationId: 'yard-11',
    dispatch_status: 'A',
    isPartialTripLot: false,
    isTowable: 'Y',
    jobUpdateTime: '2018-01-15T22: 38: 49Z',
    lossType: 'C - COLLISION',
    lotStage: 20,
    lotTripId: 7244872874,
    make: 'HOND',
    model: 'ACCORD',
    number: 52780468,
    pickupNotes:
      'Meanwhile, the poor Babel fish, by effectively removing all barriers to communication between different races and cultures, has caused more and bloodier wars than anything else in the history of creation.',
    pickupPhoneNumber: {
      areaCode: '707',
      extension: '',
      line: '5960907',
    },
    promisedTripDate: '2018-01-17',
    responsible_party_name: 'April Ludgate',
    tripId: 'sxparia-temp',
    scheduledTimeFrom: '',
    scheduledTimeTo: '',
    sellerNumber: 'JST1',
    sellerReference: '',
    source: {
      accurate: true,
      city: 'HOUSTON',
      crossstreet: '',
      exists: false,
      lat: 29.6883961,
      line1: 'TEST',
      line2: '',
      lng: -95.5288569,
      name: 'TEST HOUSTON',
      partial_match: true,
      residence: 'Y',
      state: 'TX',
      zip: '77074',
      zpp: '',
      paymentTypesAccepted: {
        card: true,
        check: true,
        cash: true,
      },
    },
    sourceLocationId: 'loc-7244872351',
    subhaulerUser: 'A & S TOW',
    suffix: 'Q',
    towType: 'Standard',
    trackupdatedBy: 'CALL FOR RELEASE',
    tripStatus: 'W',
    tripType: 'P',
    tripZone: 6,
    updateByUser: 'OPSPORTAL-sxparia',
    updatedBy: 'realtime',
    vehicleType: 'V - AUTOMOBILE',
    yardNumber: 11,
    year: 2005,
    forms: {},
    status: 'assigned',
    issue: {},
  },
  {
    cashTag: '',
    chargesDue: '$100.00',
    clientUpdateTime: '2018-01-16T08: 06: 04Z',
    colors: 'BURN',
    damageCode: 'AO',
    description: '12 AUDI A3 BURN',
    destination: {
      accurate: true,
      city: 'HOUSTON',
      crossstreet: 'USA',
      exists: true,
      lat: 29.9685949,
      line1: '1655 RANKIN ROAD',
      line2: '',
      lng: -95.37359819999999,
      name: 'TX - HOUSTON',
      pano_id: 'YD4jHCnSbHoHpqDhw01sdA',
      partial_match: true,
      state: 'TX',
      zip: '77073',
      zpp: '',
    },
    destinationLocationId: 'yard-11',
    dispatch_status: 'A',
    isPartialTripLot: false,
    isTowable: 'Y',
    jobUpdateTime: '2018-01-16T00: 06: 01Z',
    lossType: 'C - COLLISION',
    lotStage: 28,
    lotTripId: 7244873356,
    make: 'AUDI',
    model: 'A3',
    number: 52780608,
    pickupNotes:
      '“Space,” it says, “is big. Really big. You just won’t believe how vastly, hugely, mindbogglingly big it is. I mean, you may think it’s a long way down the road to the chemist’s, but that’s just peanuts to space.”',
    pickupPhoneNumber: {
      areaCode: '916',
      extension: '',
      line: '6233592',
    },
    promisedTripDate: '2018-01-22',
    responsible_party_name: 'April Ludgate',
    tripId: 'SHPANDEY-1516089874537',
    scheduledTimeFrom: '',
    scheduledTimeTo: '',
    sellerNumber: 'FRR1',
    sellerReference: '',
    source: {
      accurate: true,
      city: 'WEAVERVILLE',
      crossstreet: '',
      exists: false,
      lat: 40.7293947,
      line1: '1819 MAIN ST (EAST SIDE)',
      line2: '',
      lng: -122.9384955,
      name: 'WEAVERVILLE GARAGE',
      partial_match: true,
      residence: 'N',
      state: 'CA',
      zip: '96093',
      zpp: '',
      paymentTypesAccepted: {
        card: true,
        check: true,
        cash: true,
      },
    },
    sourceLocationId: 'loc-7242686428',
    subhaulerContact: {
      areaCode: '361',
      line: '8537323',
    },
    subhaulerUser: 'A & S TOW',
    suffix: 'Q',
    towType: 'Standard',
    trackupdatedBy: 'CALL FOR RELEASE',
    tripStatus: 'P',
    tripType: 'P',
    tripZone: 99,
    updateByUser: 'REALTIME',
    updatedBy: 'realtime',
    vehicleType: 'V - AUTOMOBILE',
    yardNumber: 11,
    year: 2012,
    forms: {},
    status: 'assigned',
    issue: {},
  },
  {
    cashTag: '',
    chargesDue: '$100.00',
    clientUpdateTime: '2018-01-16T08: 13: 19Z',
    colors: 'BURN',
    damageCode: 'AO',
    description: '12 AUDI A3 BURN',
    destination: {
      accurate: true,
      city: 'HOUSTON',
      crossstreet: 'USA',
      exists: true,
      lat: 29.9685949,
      line1: '1655 RANKIN ROAD',
      line2: '',
      lng: -95.37359819999999,
      name: 'TX - HOUSTON',
      pano_id: 'YD4jHCnSbHoHpqDhw01sdA',
      partial_match: true,
      state: 'TX',
      zip: '77073',
      zpp: '',
    },
    destinationLocationId: 'yard-11',
    dispatch_status: 'A',
    isPartialTripLot: false,
    isTowable: 'Y',
    jobUpdateTime: '2018-01-16T00: 13: 15Z',
    lossType: 'C - COLLISION',
    lotStage: 28,
    lotTripId: 7244873997,
    make: 'AUDI',
    model: 'A3',
    number: 52780688,
    pickupNotes:
      'There is a theory which states that if ever anyone discovers exactly what the Universe is for and why it is here, it will instantly disappear and be replaced by something even more bizarre and inexplicable. There is another theory which states that this has already happened',
    pickupPhoneNumber: {
      areaCode: '916',
      extension: '',
      line: '6233592',
    },
    promisedTripDate: '2018-01-23',
    responsible_party_name: 'April Ludgate',
    tripId: 'SHPANDEY-1516090307769',
    scheduledTimeFrom: '',
    scheduledTimeTo: '',
    sellerNumber: 'FRR1',
    sellerReference: '',
    source: {
      accurate: true,
      city: 'WEAVERVILLE',
      crossstreet: '',
      exists: false,
      lat: 40.7293947,
      line1: '1819 MAIN ST (EAST SIDE)',
      line2: '',
      lng: -122.9384955,
      name: 'WEAVERVILLE GARAGE',
      partial_match: true,
      residence: 'N',
      state: 'CA',
      zip: '96093',
      zpp: '',
      paymentTypesAccepted: {
        card: true,
        check: true,
        cash: true,
      },
    },
    sourceLocationId: 'loc-7242686428',
    subhaulerContact: {
      areaCode: '361',
      line: '8537323',
    },
    subhaulerUser: 'A & S TOW',
    suffix: 'Q',
    towType: 'Standard',
    trackupdatedBy: 'CALL FOR RELEASE',
    tripStatus: 'P',
    tripType: 'P',
    tripZone: 99,
    updateByUser: 'REALTIME',
    updatedBy: 'realtime',
    vehicleType: 'V - AUTOMOBILE',
    yardNumber: 11,
    year: 2012,
    forms: {},
    status: 'assigned',
    issue: {},
  },
];
