export default {
  lotNumber: 12264804,
  sellernumber: 'SZ94',
  buyerNumber: '0',
  lotNotes: [
    {
      lotNumber: null,
      type: null,
      seqNbr: '1',
      autoCode: 'CRTD',
      notes:
        '*AUTO: CREATED BY TMTODD AT 15:12:10 ET\n*FILE: ************************************************************\n*FILE: ************************************************************\n*FILE: DO NOT CONTACT ADJUSTER FOR RELEASE ISSUES UNTIL 24 HOURS\n*FILE: ************************************************************',
      userId: 'TMTODD',
      userName: 'TIFFANY M. TODD',
      createTime: '2014-01-02T20:12:10Z',
      extendedNotes1: null,
      extendedNotes2: null,
    },
    {
      lotNumber: null,
      type: null,
      seqNbr: '6',
      autoCode: 'CLLR',
      notes: '*AUTO: ORIGINAL CALLER WAS PAULUS DAGBUI @ (770)418-3470',
      userId: 'TMTODD',
      userName: 'TIFFANY M. TODD',
      createTime: '2014-01-02T20:12:10Z',
      extendedNotes1: null,
      extendedNotes2: null,
    },
    {
      lotNumber: null,
      type: null,
      seqNbr: '7',
      autoCode: 'TOTL',
      notes: '*AUTO: ORIGINAL TITLE DATE ENTERED',
      userId: 'LRSHEPPARD',
      userName: 'LAYLA R. SHEPPARD',
      createTime: '2014-01-06T22:05:48Z',
      extendedNotes1: null,
      extendedNotes2: null,
    },
    {
      lotNumber: null,
      type: null,
      seqNbr: '8',
      autoCode: 'TPP1',
      notes:
        '*AUTO: TPP TRANS QTY 1, RECEIVED 1/06/14\n*AUTO: TPP POA QTY 2, RECEIVED 1/06/14\n*AUTO: TPP Other QTY 3, RECEIVED 1/06/14',
      userId: 'LRSHEPPARD',
      userName: 'LAYLA R. SHEPPARD',
      createTime: '2014-01-06T22:06:06Z',
      extendedNotes1: null,
      extendedNotes2: null,
    },
    {
      lotNumber: null,
      type: null,
      seqNbr: '10',
      autoCode: 'TPP2',
      notes: '*AUTO: TPP COMMENT: SHAWANDA WALTON\n*AUTO: TPP COMMENT: TITLE/THEFT LETTER',
      userId: 'LRSHEPPARD',
      userName: 'LAYLA R. SHEPPARD',
      createTime: '2014-01-06T22:06:06Z',
      extendedNotes1: null,
      extendedNotes2: null,
    },
    {
      lotNumber: null,
      type: null,
      seqNbr: '13',
      autoCode: 'CONC',
      notes: '*AUTO: CONTRACT CHANGED VIA CONTRACT CHANGE CHECKER',
      userId: 'ATANDRADE',
      userName: 'AVENAMAR T. ANDRADE',
      createTime: '2014-01-07T14:40:00Z',
      extendedNotes1: null,
      extendedNotes2: null,
    },
    {
      lotNumber: null,
      type: null,
      seqNbr: '14',
      autoCode: '',
      notes: 'RECEIVED TRANMITTAL REQUESTING A SALVAGE TITLE FOR STOLEN/UNRECOV',
      userId: 'HCSINYARD',
      userName: 'HCSINYARD',
      createTime: '2014-01-07T20:50:25Z',
      extendedNotes1: null,
      extendedNotes2: null,
    },
    {
      lotNumber: null,
      type: null,
      seqNbr: '15',
      autoCode: '',
      notes:
        'ERED VEHICLE.\nLEFT MESSAGE FOR ADJUSTER JENNIFER DORE, X7704183152 ADVISING NEW\nTRANSMITTAL FOR UNRECOVERED THEFT TITLE, WHICH IS A CLEAN TITLE.\nTITLE ONLY ASSIGNMENT CANNOT BE PUT ON HOLD AND WILL FOLLOW UP ON\n1/13. HS',
      userId: 'HCSINYARD',
      userName: 'HCSINYARD',
      createTime: '2014-01-07T20:51:37Z',
      extendedNotes1: null,
      extendedNotes2: null,
    },
    {
      lotNumber: null,
      type: null,
      seqNbr: '20',
      autoCode: 'CON2',
      notes: '*AUTO: STORAGE SCHEDULE CHANGED VIA CONTRACT CHANGE CHECKER',
      userId: 'LTMERCADO',
      userName: 'LEOPOLDO T. MERCADO',
      createTime: '2014-01-08T13:39:26Z',
      extendedNotes1: null,
      extendedNotes2: null,
    },
    {
      lotNumber: null,
      type: null,
      seqNbr: '21',
      autoCode: 'STGC',
      notes: '*AUTO: SELLER STORAGE THRU DATE RECALCULATED',
      userId: 'LTMERCADO',
      userName: 'LEOPOLDO T. MERCADO',
      createTime: '2014-01-08T13:39:26Z',
      extendedNotes1: null,
      extendedNotes2: null,
    },
    {
      lotNumber: null,
      type: null,
      seqNbr: '22',
      autoCode: 'ODBT',
      notes: '*AUTO: TITLE ODOMETER BRAND CHANGED FROM TO E',
      userId: 'AHWOULFE',
      userName: 'ADRIAN H. WOULFE',
      createTime: '2014-01-09T21:09:37Z',
      extendedNotes1: null,
      extendedNotes2: null,
    },
    {
      lotNumber: null,
      type: null,
      seqNbr: '23',
      autoCode: 'ODBS',
      notes: '*AUTO: STATEMENT ODOMETER BRAND CHANGED FROM TO E',
      userId: 'AHWOULFE',
      userName: 'ADRIAN H. WOULFE',
      createTime: '2014-01-09T21:09:37Z',
      extendedNotes1: null,
      extendedNotes2: null,
    },
    {
      lotNumber: null,
      type: null,
      seqNbr: '24',
      autoCode: 'ODBC',
      notes: '*AUTO: CALCULATED ODOMETER BRAND CHANGED FROM TO E',
      userId: 'AHWOULFE',
      userName: 'ADRIAN H. WOULFE',
      createTime: '2014-01-09T21:09:37Z',
      extendedNotes1: null,
      extendedNotes2: null,
    },
    {
      lotNumber: null,
      type: null,
      seqNbr: '25',
      autoCode: 'ASLN',
      notes:
        '*AUTO: SELLER NAME STATE FARM MUTUAL AUTOMOBILE INS COADDED FOR\n*AUTO:   TITLE PROCESSING',
      userId: 'AHWOULFE',
      userName: 'ADRIAN H. WOULFE',
      createTime: '2014-01-09T21:09:40Z',
      extendedNotes1: null,
      extendedNotes2: null,
    },
    {
      lotNumber: null,
      type: null,
      seqNbr: '27',
      autoCode: 'TTLI',
      notes: '*AUTO: TITLE NUMBER AND STATE ORIGINALLY ENTERED',
      userId: 'AHWOULFE',
      userName: 'ADRIAN H. WOULFE',
      createTime: '2014-01-09T21:10:01Z',
      extendedNotes1: null,
      extendedNotes2: null,
    },
    {
      lotNumber: null,
      type: null,
      seqNbr: '28',
      autoCode: 'TTLN',
      notes: '*AUTO: ORIGINAL TITLE TYPE CERTIFICATE OF TITLE ADDED',
      userId: 'AHWOULFE',
      userName: 'ADRIAN H. WOULFE',
      createTime: '2014-01-09T21:10:01Z',
      extendedNotes1: null,
      extendedNotes2: null,
    },
    {
      lotNumber: null,
      type: null,
      seqNbr: '29',
      autoCode: 'TTLO',
      notes: '*AUTO: SALE TITLE TYPE CERT OF TITLE-STOLEN/UNRE ADDED',
      userId: 'AHWOULFE',
      userName: 'ADRIAN H. WOULFE',
      createTime: '2014-01-09T21:10:01Z',
      extendedNotes1: null,
      extendedNotes2: null,
    },
    {
      lotNumber: null,
      type: null,
      seqNbr: '30',
      autoCode: 'TTLM',
      notes: '*AUTO: SUBMITTED TO DMV WHEN BUNDLE CLOSED',
      userId: 'AHWOULFE',
      userName: 'ADRIAN H. WOULFE',
      createTime: '2014-01-09T22:06:28Z',
      extendedNotes1: null,
      extendedNotes2: null,
    },
    {
      lotNumber: null,
      type: null,
      seqNbr: '31',
      autoCode: 'TOAC',
      notes: '*AUTO: TITLE ONLY AUTO-CLOSED AFTER TITLE SUBMITTED TO STATE',
      userId: 'MISSEC',
      userName: 'MIS SECURITY OFFICER',
      createTime: '2014-01-10T04:06:13Z',
      extendedNotes1: null,
      extendedNotes2: null,
    },
    {
      lotNumber: null,
      type: null,
      seqNbr: '32',
      autoCode: 'SLPA',
      notes: '*AUTO: $29 SELLER PAYMENT APPLIED.',
      userId: 'LMMONTALVO',
      userName: 'LISA M. MONTALVO',
      createTime: '2014-01-30T15:59:01Z',
      extendedNotes1: null,
      extendedNotes2: null,
    },
  ],
  buyerNotes: [],
  sellerNotes: [
    {
      lotNumber: null,
      type: null,
      seqNbr: '1',
      autoCode: 'TDIR',
      notes: '*AUTO: TD Authorized Changed from Y',
      userId: 'SXSAHA',
      userName: 'SAHELI X. SAHA',
      createTime: '2016-04-29T11:24:46Z',
      extendedNotes1: null,
      extendedNotes2: null,
    },
    {
      lotNumber: null,
      type: null,
      seqNbr: '2',
      autoCode: 'OSLR',
      notes: '*AUTO: NEW ADJUSTER FFHU TRFW ADDED BY SELLER PROFILE DEMOA',
      userId: 'DEMOA',
      userName: 'DEMO   DEMOA',
      createTime: '2016-06-14T11:27:09Z',
      extendedNotes1: null,
      extendedNotes2: null,
    },
    {
      lotNumber: null,
      type: null,
      seqNbr: '3',
      autoCode: 'SLR1',
      notes: '*AUTO: CLAIM MASK OVERRIDE CHANGED FROM TO N.',
      userId: 'SXSAHA',
      userName: 'SAHELI X. SAHA',
      createTime: '2017-01-24T09:50:59Z',
      extendedNotes1: null,
      extendedNotes2: null,
    },
    {
      lotNumber: null,
      type: null,
      seqNbr: '4',
      autoCode: '',
      notes: 'TESTING',
      userId: 'RAMEHTA',
      userName: 'RAM MEHTA',
      createTime: '2017-02-20T22:57:33Z',
      extendedNotes1: null,
      extendedNotes2: null,
    },
    {
      lotNumber: null,
      type: null,
      seqNbr: '5',
      autoCode: 'OSLR',
      notes: '*AUTO: NEW ADJUSTER QEWTQG ASDGQASD ADDED BY SELLER PROFILE DEMO',
      userId: 'DEMO',
      userName: 'COPART DEMO',
      createTime: '2017-03-01T20:36:20Z',
      extendedNotes1: null,
      extendedNotes2: null,
    },
    {
      lotNumber: null,
      type: null,
      seqNbr: '6',
      autoCode: '',
      notes: 'TESTING CHANDRA',
      userId: 'RAMEHTA',
      userName: 'RAM MEHTA',
      createTime: '2017-03-01T21:28:21Z',
      extendedNotes1: null,
      extendedNotes2: null,
    },
    {
      lotNumber: null,
      type: null,
      seqNbr: '7',
      autoCode: 'SLR1',
      notes: '*AUTO: TITLE CHARGES TYPE CHANGED FROM 4 TO 1.',
      userId: 'KCTHOMAS',
      userName: 'KARLA C. THOMAS',
      createTime: '2017-03-24T22:52:33Z',
      extendedNotes1: null,
      extendedNotes2: null,
    },
    {
      lotNumber: null,
      type: null,
      seqNbr: '8',
      autoCode: 'OSLR',
      notes: '*AUTO: NEW ADJUSTER TEST AK ADDED BY SELLER PROFILE DEMO',
      userId: 'DEMO',
      userName: 'COPART DEMO',
      createTime: '2017-07-07T19:25:03Z',
      extendedNotes1: null,
      extendedNotes2: null,
    },
    {
      lotNumber: null,
      type: null,
      seqNbr: '9',
      autoCode: 'SLR1',
      notes: '*AUTO: CLAIM MASK OVERRIDE CHANGED FROM N TO Y.',
      userId: 'SXPARIA',
      userName: 'SUJAYANANDA X. PARIA',
      createTime: '2017-10-31T07:38:42Z',
      extendedNotes1: null,
      extendedNotes2: null,
    },
    {
      lotNumber: null,
      type: null,
      seqNbr: '10',
      autoCode: 'SLR1',
      notes: '*AUTO: DEDUCT TITLE FEES CHANGED FROM N TO Y.',
      userId: 'SXPARIA',
      userName: 'SUJAYANANDA X. PARIA',
      createTime: '2017-10-31T07:39:45Z',
      extendedNotes1: null,
      extendedNotes2: null,
    },
    {
      lotNumber: null,
      type: null,
      seqNbr: '11',
      autoCode: 'SLR1',
      notes: '*AUTO: DEDUCT TITLE FEES CHANGED FROM Y TO N.',
      userId: 'SXPARIA',
      userName: 'SUJAYANANDA X. PARIA',
      createTime: '2017-10-31T07:49:58Z',
      extendedNotes1: null,
      extendedNotes2: null,
    },
    {
      lotNumber: null,
      type: null,
      seqNbr: '12',
      autoCode: 'SLR2',
      notes: '*AUTO: SELLER CONTRACT CAT TTL PGM 301 CHANGED TO 100 FOR YARD\n*AUTO:   146.',
      userId: 'DENIGHERBO',
      userName: 'DIANA E. NIGHERBON',
      createTime: '2017-11-09T23:20:41Z',
      extendedNotes1: null,
      extendedNotes2: null,
    },
  ],
  dispatchNotes: null,
  billingNotes: null,
  titleNotes: [
    {
      lotNumber: null,
      type: null,
      seqNbr: '1',
      autoCode: null,
      notes:
        '(1-855-472-0428)  ANY QUESTION/ISSUE REGARDING TITLE PAPERWORK, OR TO LEARN WHO THE ADJUSTER IS ON A SPECIFIC CLAIM',
      userId: 'YLVIDAL',
      userName: 'YOKER L. VIDAL',
      createTime: '2013-07-16T19:15:08Z',
      extendedNotes1: null,
      extendedNotes2: null,
    },
  ],
  extendedNotes: null,
  locationNotes: [],
};
