// flow-typed signature: 98df28475295c8fb141edbbf17da9f2f
// flow-typed version: <<STUB>>/react-native-navigation_vgit://github.com/himanshusoni/react-native-navigation.git/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-navigation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-navigation' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-navigation/docs/sw' {
  declare module.exports: any;
}

declare module 'react-native-navigation/example/index.android' {
  declare module.exports: any;
}

declare module 'react-native-navigation/example/index.ios' {
  declare module.exports: any;
}

declare module 'react-native-navigation/example/scripts/postinstall' {
  declare module.exports: any;
}

declare module 'react-native-navigation/example/src/app' {
  declare module.exports: any;
}

declare module 'react-native-navigation/example/src/components/Row' {
  declare module.exports: any;
}

declare module 'react-native-navigation/example/src/screens/Actions' {
  declare module.exports: any;
}

declare module 'react-native-navigation/example/src/screens/index' {
  declare module.exports: any;
}

declare module 'react-native-navigation/example/src/screens/NavigationTypes' {
  declare module.exports: any;
}

declare module 'react-native-navigation/example/src/screens/Transitions' {
  declare module.exports: any;
}

declare module 'react-native-navigation/example/src/screens/transitions/CollapsingHeader' {
  declare module.exports: any;
}

declare module 'react-native-navigation/example/src/screens/transitions/SharedElementTransitions' {
  declare module.exports: any;
}

declare module 'react-native-navigation/example/src/screens/transitions/sharedElementTransitions/Cards/Cards' {
  declare module.exports: any;
}

declare module 'react-native-navigation/example/src/screens/transitions/sharedElementTransitions/Cards/Info' {
  declare module.exports: any;
}

declare module 'react-native-navigation/example/src/screens/transitions/sharedElementTransitions/Masonry/images' {
  declare module.exports: any;
}

declare module 'react-native-navigation/example/src/screens/transitions/sharedElementTransitions/Masonry/Item' {
  declare module.exports: any;
}

declare module 'react-native-navigation/example/src/screens/transitions/sharedElementTransitions/Masonry/Masonry' {
  declare module.exports: any;
}

declare module 'react-native-navigation/example/src/screens/transitions/sharedElementTransitions/Profiles/data' {
  declare module.exports: any;
}

declare module 'react-native-navigation/example/src/screens/transitions/sharedElementTransitions/Profiles/Profiles' {
  declare module.exports: any;
}

declare module 'react-native-navigation/example/src/screens/types/CustomButtonScreen' {
  declare module.exports: any;
}

declare module 'react-native-navigation/example/src/screens/types/CustomTopBar' {
  declare module.exports: any;
}

declare module 'react-native-navigation/example/src/screens/types/CustomTopBarScreen' {
  declare module.exports: any;
}

declare module 'react-native-navigation/example/src/screens/types/Drawer' {
  declare module.exports: any;
}

declare module 'react-native-navigation/example/src/screens/types/DummyScreen' {
  declare module.exports: any;
}

declare module 'react-native-navigation/example/src/screens/types/LightBox' {
  declare module.exports: any;
}

declare module 'react-native-navigation/example/src/screens/types/ListScreen' {
  declare module.exports: any;
}

declare module 'react-native-navigation/example/src/screens/types/Modal' {
  declare module.exports: any;
}

declare module 'react-native-navigation/example/src/screens/types/Notification' {
  declare module.exports: any;
}

declare module 'react-native-navigation/example/src/screens/types/Push' {
  declare module.exports: any;
}

declare module 'react-native-navigation/example/src/screens/types/tabs/TabOne' {
  declare module.exports: any;
}

declare module 'react-native-navigation/example/src/screens/types/tabs/TabTwo' {
  declare module.exports: any;
}

declare module 'react-native-navigation/example/src/screens/types/TopTabs' {
  declare module.exports: any;
}

declare module 'react-native-navigation/example/test/e2e/init' {
  declare module.exports: any;
}

declare module 'react-native-navigation/example/test/e2e/sanity.test' {
  declare module.exports: any;
}

declare module 'react-native-navigation/old-example-redux/index.android' {
  declare module.exports: any;
}

declare module 'react-native-navigation/old-example-redux/index.ios' {
  declare module.exports: any;
}

declare module 'react-native-navigation/old-example-redux/src/app' {
  declare module.exports: any;
}

declare module 'react-native-navigation/old-example-redux/src/components/ExampleComponent' {
  declare module.exports: any;
}

declare module 'react-native-navigation/old-example-redux/src/reducers/app/actions' {
  declare module.exports: any;
}

declare module 'react-native-navigation/old-example-redux/src/reducers/app/actionTypes' {
  declare module.exports: any;
}

declare module 'react-native-navigation/old-example-redux/src/reducers/app/reducer' {
  declare module.exports: any;
}

declare module 'react-native-navigation/old-example-redux/src/reducers/counter/actions' {
  declare module.exports: any;
}

declare module 'react-native-navigation/old-example-redux/src/reducers/counter/actionTypes' {
  declare module.exports: any;
}

declare module 'react-native-navigation/old-example-redux/src/reducers/counter/reducer' {
  declare module.exports: any;
}

declare module 'react-native-navigation/old-example-redux/src/reducers/index' {
  declare module.exports: any;
}

declare module 'react-native-navigation/old-example-redux/src/screens/BottomTabsSideMenu' {
  declare module.exports: any;
}

declare module 'react-native-navigation/old-example-redux/src/screens/FirstTabScreen' {
  declare module.exports: any;
}

declare module 'react-native-navigation/old-example-redux/src/screens/index' {
  declare module.exports: any;
}

declare module 'react-native-navigation/old-example-redux/src/screens/ListScreen' {
  declare module.exports: any;
}

declare module 'react-native-navigation/old-example-redux/src/screens/LoginScreen' {
  declare module.exports: any;
}

declare module 'react-native-navigation/old-example-redux/src/screens/PushedScreen' {
  declare module.exports: any;
}

declare module 'react-native-navigation/old-example-redux/src/screens/SecondTabScreen' {
  declare module.exports: any;
}

declare module 'react-native-navigation/old-example-redux/src/screens/SideMenu' {
  declare module.exports: any;
}

declare module 'react-native-navigation/old-example-redux/src/screens/TopTabsScreen' {
  declare module.exports: any;
}

declare module 'react-native-navigation/scripts/release' {
  declare module.exports: any;
}

declare module 'react-native-navigation/src/deprecated/controllers/Constants' {
  declare module.exports: any;
}

declare module 'react-native-navigation/src/deprecated/controllers/index' {
  declare module.exports: any;
}

declare module 'react-native-navigation/src/deprecated/controllers/utils' {
  declare module.exports: any;
}

declare module 'react-native-navigation/src/deprecated/indexDeprecated.android' {
  declare module.exports: any;
}

declare module 'react-native-navigation/src/deprecated/indexDeprecated.ios' {
  declare module.exports: any;
}

declare module 'react-native-navigation/src/deprecated/platformSpecificDeprecated.android' {
  declare module.exports: any;
}

declare module 'react-native-navigation/src/deprecated/platformSpecificDeprecated.ios' {
  declare module.exports: any;
}

declare module 'react-native-navigation/src/index' {
  declare module.exports: any;
}

declare module 'react-native-navigation/src/NativeEventsReceiver' {
  declare module.exports: any;
}

declare module 'react-native-navigation/src/Navigation' {
  declare module.exports: any;
}

declare module 'react-native-navigation/src/platformSpecific.android' {
  declare module.exports: any;
}

declare module 'react-native-navigation/src/platformSpecific.ios' {
  declare module.exports: any;
}

declare module 'react-native-navigation/src/PropRegistry' {
  declare module.exports: any;
}

declare module 'react-native-navigation/src/Screen' {
  declare module.exports: any;
}

declare module 'react-native-navigation/src/ScreenVisibilityListener' {
  declare module.exports: any;
}

declare module 'react-native-navigation/src/views/sharedElementTransition.android' {
  declare module.exports: any;
}

declare module 'react-native-navigation/src/views/sharedElementTransition.ios' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-navigation/docs/sw.js' {
  declare module.exports: $Exports<'react-native-navigation/docs/sw'>;
}
declare module 'react-native-navigation/example/index.android.js' {
  declare module.exports: $Exports<'react-native-navigation/example/index.android'>;
}
declare module 'react-native-navigation/example/index.ios.js' {
  declare module.exports: $Exports<'react-native-navigation/example/index.ios'>;
}
declare module 'react-native-navigation/example/scripts/postinstall.js' {
  declare module.exports: $Exports<'react-native-navigation/example/scripts/postinstall'>;
}
declare module 'react-native-navigation/example/src/app.js' {
  declare module.exports: $Exports<'react-native-navigation/example/src/app'>;
}
declare module 'react-native-navigation/example/src/components/Row.js' {
  declare module.exports: $Exports<'react-native-navigation/example/src/components/Row'>;
}
declare module 'react-native-navigation/example/src/screens/Actions.js' {
  declare module.exports: $Exports<'react-native-navigation/example/src/screens/Actions'>;
}
declare module 'react-native-navigation/example/src/screens/index.js' {
  declare module.exports: $Exports<'react-native-navigation/example/src/screens/index'>;
}
declare module 'react-native-navigation/example/src/screens/NavigationTypes.js' {
  declare module.exports: $Exports<'react-native-navigation/example/src/screens/NavigationTypes'>;
}
declare module 'react-native-navigation/example/src/screens/Transitions.js' {
  declare module.exports: $Exports<'react-native-navigation/example/src/screens/Transitions'>;
}
declare module 'react-native-navigation/example/src/screens/transitions/CollapsingHeader.js' {
  declare module.exports: $Exports<'react-native-navigation/example/src/screens/transitions/CollapsingHeader'>;
}
declare module 'react-native-navigation/example/src/screens/transitions/SharedElementTransitions.js' {
  declare module.exports: $Exports<'react-native-navigation/example/src/screens/transitions/SharedElementTransitions'>;
}
declare module 'react-native-navigation/example/src/screens/transitions/sharedElementTransitions/Cards/Cards.js' {
  declare module.exports: $Exports<'react-native-navigation/example/src/screens/transitions/sharedElementTransitions/Cards/Cards'>;
}
declare module 'react-native-navigation/example/src/screens/transitions/sharedElementTransitions/Cards/Info.js' {
  declare module.exports: $Exports<'react-native-navigation/example/src/screens/transitions/sharedElementTransitions/Cards/Info'>;
}
declare module 'react-native-navigation/example/src/screens/transitions/sharedElementTransitions/Masonry/images.js' {
  declare module.exports: $Exports<'react-native-navigation/example/src/screens/transitions/sharedElementTransitions/Masonry/images'>;
}
declare module 'react-native-navigation/example/src/screens/transitions/sharedElementTransitions/Masonry/Item.js' {
  declare module.exports: $Exports<'react-native-navigation/example/src/screens/transitions/sharedElementTransitions/Masonry/Item'>;
}
declare module 'react-native-navigation/example/src/screens/transitions/sharedElementTransitions/Masonry/Masonry.js' {
  declare module.exports: $Exports<'react-native-navigation/example/src/screens/transitions/sharedElementTransitions/Masonry/Masonry'>;
}
declare module 'react-native-navigation/example/src/screens/transitions/sharedElementTransitions/Profiles/data.js' {
  declare module.exports: $Exports<'react-native-navigation/example/src/screens/transitions/sharedElementTransitions/Profiles/data'>;
}
declare module 'react-native-navigation/example/src/screens/transitions/sharedElementTransitions/Profiles/Profiles.js' {
  declare module.exports: $Exports<'react-native-navigation/example/src/screens/transitions/sharedElementTransitions/Profiles/Profiles'>;
}
declare module 'react-native-navigation/example/src/screens/types/CustomButtonScreen.js' {
  declare module.exports: $Exports<'react-native-navigation/example/src/screens/types/CustomButtonScreen'>;
}
declare module 'react-native-navigation/example/src/screens/types/CustomTopBar.js' {
  declare module.exports: $Exports<'react-native-navigation/example/src/screens/types/CustomTopBar'>;
}
declare module 'react-native-navigation/example/src/screens/types/CustomTopBarScreen.js' {
  declare module.exports: $Exports<'react-native-navigation/example/src/screens/types/CustomTopBarScreen'>;
}
declare module 'react-native-navigation/example/src/screens/types/Drawer.js' {
  declare module.exports: $Exports<'react-native-navigation/example/src/screens/types/Drawer'>;
}
declare module 'react-native-navigation/example/src/screens/types/DummyScreen.js' {
  declare module.exports: $Exports<'react-native-navigation/example/src/screens/types/DummyScreen'>;
}
declare module 'react-native-navigation/example/src/screens/types/LightBox.js' {
  declare module.exports: $Exports<'react-native-navigation/example/src/screens/types/LightBox'>;
}
declare module 'react-native-navigation/example/src/screens/types/ListScreen.js' {
  declare module.exports: $Exports<'react-native-navigation/example/src/screens/types/ListScreen'>;
}
declare module 'react-native-navigation/example/src/screens/types/Modal.js' {
  declare module.exports: $Exports<'react-native-navigation/example/src/screens/types/Modal'>;
}
declare module 'react-native-navigation/example/src/screens/types/Notification.js' {
  declare module.exports: $Exports<'react-native-navigation/example/src/screens/types/Notification'>;
}
declare module 'react-native-navigation/example/src/screens/types/Push.js' {
  declare module.exports: $Exports<'react-native-navigation/example/src/screens/types/Push'>;
}
declare module 'react-native-navigation/example/src/screens/types/tabs/TabOne.js' {
  declare module.exports: $Exports<'react-native-navigation/example/src/screens/types/tabs/TabOne'>;
}
declare module 'react-native-navigation/example/src/screens/types/tabs/TabTwo.js' {
  declare module.exports: $Exports<'react-native-navigation/example/src/screens/types/tabs/TabTwo'>;
}
declare module 'react-native-navigation/example/src/screens/types/TopTabs.js' {
  declare module.exports: $Exports<'react-native-navigation/example/src/screens/types/TopTabs'>;
}
declare module 'react-native-navigation/example/test/e2e/init.js' {
  declare module.exports: $Exports<'react-native-navigation/example/test/e2e/init'>;
}
declare module 'react-native-navigation/example/test/e2e/sanity.test.js' {
  declare module.exports: $Exports<'react-native-navigation/example/test/e2e/sanity.test'>;
}
declare module 'react-native-navigation/old-example-redux/index.android.js' {
  declare module.exports: $Exports<'react-native-navigation/old-example-redux/index.android'>;
}
declare module 'react-native-navigation/old-example-redux/index.ios.js' {
  declare module.exports: $Exports<'react-native-navigation/old-example-redux/index.ios'>;
}
declare module 'react-native-navigation/old-example-redux/src/app.js' {
  declare module.exports: $Exports<'react-native-navigation/old-example-redux/src/app'>;
}
declare module 'react-native-navigation/old-example-redux/src/components/ExampleComponent.js' {
  declare module.exports: $Exports<'react-native-navigation/old-example-redux/src/components/ExampleComponent'>;
}
declare module 'react-native-navigation/old-example-redux/src/reducers/app/actions.js' {
  declare module.exports: $Exports<'react-native-navigation/old-example-redux/src/reducers/app/actions'>;
}
declare module 'react-native-navigation/old-example-redux/src/reducers/app/actionTypes.js' {
  declare module.exports: $Exports<'react-native-navigation/old-example-redux/src/reducers/app/actionTypes'>;
}
declare module 'react-native-navigation/old-example-redux/src/reducers/app/reducer.js' {
  declare module.exports: $Exports<'react-native-navigation/old-example-redux/src/reducers/app/reducer'>;
}
declare module 'react-native-navigation/old-example-redux/src/reducers/counter/actions.js' {
  declare module.exports: $Exports<'react-native-navigation/old-example-redux/src/reducers/counter/actions'>;
}
declare module 'react-native-navigation/old-example-redux/src/reducers/counter/actionTypes.js' {
  declare module.exports: $Exports<'react-native-navigation/old-example-redux/src/reducers/counter/actionTypes'>;
}
declare module 'react-native-navigation/old-example-redux/src/reducers/counter/reducer.js' {
  declare module.exports: $Exports<'react-native-navigation/old-example-redux/src/reducers/counter/reducer'>;
}
declare module 'react-native-navigation/old-example-redux/src/reducers/index.js' {
  declare module.exports: $Exports<'react-native-navigation/old-example-redux/src/reducers/index'>;
}
declare module 'react-native-navigation/old-example-redux/src/screens/BottomTabsSideMenu.js' {
  declare module.exports: $Exports<'react-native-navigation/old-example-redux/src/screens/BottomTabsSideMenu'>;
}
declare module 'react-native-navigation/old-example-redux/src/screens/FirstTabScreen.js' {
  declare module.exports: $Exports<'react-native-navigation/old-example-redux/src/screens/FirstTabScreen'>;
}
declare module 'react-native-navigation/old-example-redux/src/screens/index.js' {
  declare module.exports: $Exports<'react-native-navigation/old-example-redux/src/screens/index'>;
}
declare module 'react-native-navigation/old-example-redux/src/screens/ListScreen.js' {
  declare module.exports: $Exports<'react-native-navigation/old-example-redux/src/screens/ListScreen'>;
}
declare module 'react-native-navigation/old-example-redux/src/screens/LoginScreen.js' {
  declare module.exports: $Exports<'react-native-navigation/old-example-redux/src/screens/LoginScreen'>;
}
declare module 'react-native-navigation/old-example-redux/src/screens/PushedScreen.js' {
  declare module.exports: $Exports<'react-native-navigation/old-example-redux/src/screens/PushedScreen'>;
}
declare module 'react-native-navigation/old-example-redux/src/screens/SecondTabScreen.js' {
  declare module.exports: $Exports<'react-native-navigation/old-example-redux/src/screens/SecondTabScreen'>;
}
declare module 'react-native-navigation/old-example-redux/src/screens/SideMenu.js' {
  declare module.exports: $Exports<'react-native-navigation/old-example-redux/src/screens/SideMenu'>;
}
declare module 'react-native-navigation/old-example-redux/src/screens/TopTabsScreen.js' {
  declare module.exports: $Exports<'react-native-navigation/old-example-redux/src/screens/TopTabsScreen'>;
}
declare module 'react-native-navigation/scripts/release.js' {
  declare module.exports: $Exports<'react-native-navigation/scripts/release'>;
}
declare module 'react-native-navigation/src/deprecated/controllers/Constants.js' {
  declare module.exports: $Exports<'react-native-navigation/src/deprecated/controllers/Constants'>;
}
declare module 'react-native-navigation/src/deprecated/controllers/index.js' {
  declare module.exports: $Exports<'react-native-navigation/src/deprecated/controllers/index'>;
}
declare module 'react-native-navigation/src/deprecated/controllers/utils.js' {
  declare module.exports: $Exports<'react-native-navigation/src/deprecated/controllers/utils'>;
}
declare module 'react-native-navigation/src/deprecated/indexDeprecated.android.js' {
  declare module.exports: $Exports<'react-native-navigation/src/deprecated/indexDeprecated.android'>;
}
declare module 'react-native-navigation/src/deprecated/indexDeprecated.ios.js' {
  declare module.exports: $Exports<'react-native-navigation/src/deprecated/indexDeprecated.ios'>;
}
declare module 'react-native-navigation/src/deprecated/platformSpecificDeprecated.android.js' {
  declare module.exports: $Exports<'react-native-navigation/src/deprecated/platformSpecificDeprecated.android'>;
}
declare module 'react-native-navigation/src/deprecated/platformSpecificDeprecated.ios.js' {
  declare module.exports: $Exports<'react-native-navigation/src/deprecated/platformSpecificDeprecated.ios'>;
}
declare module 'react-native-navigation/src/index.js' {
  declare module.exports: $Exports<'react-native-navigation/src/index'>;
}
declare module 'react-native-navigation/src/NativeEventsReceiver.js' {
  declare module.exports: $Exports<'react-native-navigation/src/NativeEventsReceiver'>;
}
declare module 'react-native-navigation/src/Navigation.js' {
  declare module.exports: $Exports<'react-native-navigation/src/Navigation'>;
}
declare module 'react-native-navigation/src/platformSpecific.android.js' {
  declare module.exports: $Exports<'react-native-navigation/src/platformSpecific.android'>;
}
declare module 'react-native-navigation/src/platformSpecific.ios.js' {
  declare module.exports: $Exports<'react-native-navigation/src/platformSpecific.ios'>;
}
declare module 'react-native-navigation/src/PropRegistry.js' {
  declare module.exports: $Exports<'react-native-navigation/src/PropRegistry'>;
}
declare module 'react-native-navigation/src/Screen.js' {
  declare module.exports: $Exports<'react-native-navigation/src/Screen'>;
}
declare module 'react-native-navigation/src/ScreenVisibilityListener.js' {
  declare module.exports: $Exports<'react-native-navigation/src/ScreenVisibilityListener'>;
}
declare module 'react-native-navigation/src/views/sharedElementTransition.android.js' {
  declare module.exports: $Exports<'react-native-navigation/src/views/sharedElementTransition.android'>;
}
declare module 'react-native-navigation/src/views/sharedElementTransition.ios.js' {
  declare module.exports: $Exports<'react-native-navigation/src/views/sharedElementTransition.ios'>;
}
