// flow-typed signature: 52ab22ff318167c55272223410024f71
// flow-typed version: <<STUB>>/render-if_v^0.1.1/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'render-if'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'render-if' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'render-if/lib/renderIf' {
  declare module.exports: any;
}

declare module 'render-if/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'render-if/lib/renderIf.js' {
  declare module.exports: $Exports<'render-if/lib/renderIf'>;
}
declare module 'render-if/test.js' {
  declare module.exports: $Exports<'render-if/test'>;
}
