export default {
  id: 123,
  // name: ?,
  tripDate: '2017-09-12',
  towTruckType: 'Foo Type',
  lots: [
    {
      cashtag: '$',
      damageCode: 'UK',
      description: '03 JAGU X-TYPE UK',
      destination: {
        accurate: true,
        city: 'GRAND PRAIRIE',
        exists: true,
        lat: 32.7422329,
        line1: '505 IDLEWILD ROAD',
        line2: '',
        lng: -96.9529093,
        name: 'TX - DALLAS(CONTACT SUNIRMAL)',
        panoId: 'obmSu0ETrHvx6BA0J13D3w',
        partialMatch: true,
        state: 'TX',
        zip: '75051',
        zpp: '',
      },
      destinationLocationId: 'yard-12',
      isTowable: 'Y',
      jobUpdateTime: '2017-08-02T22:04:13Z',
      lossType: 'D - DONATION',
      lotStage: 28,
      lotTripId: 4645642404,
      make: 'JAGU',
      model: 'X-TYPE',
      number: 50049796,
      pickupPhoneNumber: {
        area_code: '978',
        extension: '',
        line: '9789789',
      },
      promisedTripDate: '2017-10-24',
      sellerNumber: '1081',
      sellerReference: 'M5678 S1987',
      source: {
        accurate: true,
        city: 'DALLAS',
        crossstreet: '',
        exists: true,
        lat: 32.9194863,
        line1: '8000 N MACARTHUR BLVD',
        line2: '',
        lng: -96.95789289999999,
        name: 'JUNSEVENTEETH',
        panoId: 'XSFfCOFnr-E1OsaLnfiS7A',
        partialMatch: true,
        state: 'TX',
        zip: '75254',
        zpp: '',
      },
      sourceLocationId: 'loc-4645642397',
      subhaulerContact: {
        areaCode: '610',
        line: '9605463',
      },
      subhaulerUser: 'A+C TOW NJ',
      suffix: 'X',
      towType: 'Standard',
      tripStatus: 'P',
      tripType: 'P',
      tripZone: 4,
      vehicleType: 'V - AUTOMOBILE',
      yardNumber: '12',
      year: 2003,
    },
    {
      cashtag: '$',
      damageCode: 'BC',
      description: '11 ACUR CSX BLUE',
      destination: {
        accurate: true,
        city: 'GRAND PRAIRIE',
        exists: true,
        lat: 32.7422329,
        line1: '505 IDLEWILD ROAD',
        line2: '',
        lng: -96.9529093,
        name: 'TX - DALLAS(CONTACT SUNIRMAL)',
        panoId: 'obmSu0ETrHvx6BA0J13D3w',
        partialMatch: true,
        state: 'TX',
        zip: '75051',
        zpp: '',
      },
      destinationLocationId: 'yard-12',
      isTowable: 'U',
      jobUpdateTime: '2017-10-03T16:27:11Z',
      lossType: 'C - COLLISION',
      lotStage: 28,
      lotTripId: 4657230353,
      make: 'ACUR',
      model: 'CSX',
      number: 50083046,
      pickupPhoneNumber: {
        area_code: '469',
        extension: '',
        line: '2165521',
      },
      promisedTripDate: '2017-10-24',
      sellerNumber: 'AAA1',
      sellerReference: '',
      source: {
        accurate: true,
        city: 'DALLAS',
        crossstreet: '',
        exists: false,
        lat: 32.9440568,
        line1: '14350 DALLAS PKWY',
        line2: '',
        lng: -96.8213332,
        name: 'ABC TOWING CENTER1',
        partialMatch: true,
        state: 'TX',
        zip: '75254',
        zpp: '',
      },
      sourceLocationId: 'loc-4657230352',
      subhaulerContact: {
        areaCode: '817',
        line: '5046171',
      },
      subhaulerUser: 'A & S TOW',
      suffix: 'X',
      towType: 'Standard',
      tripStatus: 'P',
      tripType: 'P',
      tripZone: 4,
      vehicleType: 'V - AUTOMOBILE',
      yardNumber: '12',
      year: 2011,
    },
    {
      buyerName: 'NEW MEMBER',
      buyerNumber: 635,
      cashtag: '',
      damageCode: 'AO',
      description: '05 HOND ACCORD RED',
      destination: {
        accurate: true,
        city: 'FAIRFIELD',
        crossstreet: 'USA',
        exists: false,
        lat: 38.2583821,
        line1: 'TEST',
        line2: '',
        lng: -122.0690702,
        name: 'NEW MEMBER',
        partialMatch: true,
        state: 'CA',
        zip: '94534',
        zpp: '',
      },
      destinationDirections: '',
      destinationLocationId: 'buyer-635',
      destinationNotes: '',
      isTowable: 'U',
      jobUpdateTime: '2017-08-17T18:51:38Z',
      lossType: 'C - COLLISION',
      lotStage: 80,
      lotTripId: 4624466037,
      make: 'HOND',
      model: 'ACCORD',
      number: 49947756,
      promisedTripDate: '2016-04-21',
      sellerNumber: 'ARON',
      sellerReference: '',
      source: {
        accurate: true,
        city: 'GRAND PRAIRIE',
        exists: true,
        lat: 32.7422329,
        line1: '505 IDLEWILD ROAD',
        line2: '',
        lng: -96.9529093,
        name: 'TX - DALLAS(CONTACT SUNIRMAL)',
        panoId: 'obmSu0ETrHvx6BA0J13D3w',
        partialMatch: true,
        state: 'TX',
        zip: '75051',
        zpp: '',
      },
      sourceLocationId: 'yard-12',
      subhaulerContact: {
        areaCode: '610',
        line: '9605463',
      },
      subhaulerUser: 'A+C TOW NJ',
      suffix: 'E',
      towType: 'Standard',
      tripStatus: 'W',
      tripType: 'D',
      tripZone: 99,
      vehicleType: 'V - AUTOMOBILE',
      yardNumber: '12',
      year: 2005,
    },
  ],
  assigneeId: 1,
};
