export default {
  vehicleDetails: [
    {
      id: 1,
      field: 'tow',
      section: 'Advance Charges Review',
      required: false,
      editable: false,
      readable: true,
      showWarning: false,
      label: 'Tow',
      type: 'label',
      key1: 'tow',
      format: 'currency',
    },
    {
      id: 2,
      field: 'labor',
      section: 'Advance Charges Review',
      required: false,
      editable: true,
      readable: true,
      showWarning: false,
      label: 'Labor',
      type: 'label',
      key1: 'labor',
      format: 'currency',
    },
    {
      id: 3,
      field: 'gate',
      section: 'Advance Charges Review',
      required: false,
      editable: true,
      readable: true,
      showWarning: false,
      label: 'Yard/Gate',
      type: 'label',
      format: 'currency',
      key1: 'gate',
    },
    {
      id: 4,
      field: 'storage_from_date',
      section: 'Advance Charges Review',
      required: false,
      editable: true,
      readable: true,
      showWarning: false,
      label: 'Storage From Date',
      type: 'label',
      format: 'date',
      key1: 'storage_from_date',
    },
    {
      id: 5,
      field: 'storage_to_date',
      section: 'Advance Charges Review',
      required: false,
      editable: true,
      readable: true,
      showWarning: false,
      label: 'Storage To Date',
      type: 'label',
      key1: 'storage_to_date',
      format: 'date',
    },
    {
      id: 6,
      field: 'storage_rate',
      section: 'Advance Charges Review',
      required: false,
      editable: true,
      readable: true,
      showWarning: false,
      label: 'Storage Rate (Per Day)',
      type: 'label',
      key1: 'storage_rate',
      format: 'currency',
    },
    {
      id: 7,
      field: 'storage_amount',
      section: 'Advance Charges Review',
      required: false,
      editable: true,
      readable: true,
      showWarning: false,
      label: 'Storage Amount',
      type: 'label',
      key1: 'storage_amount',
      format: 'currency',
    },
    {
      id: 8,
      field: 'second_storage_from_date',
      section: 'Advance Charges Review',
      required: false,
      editable: true,
      readable: true,
      showWarning: false,
      label: 'Second Storage From Date',
      type: 'label',
      format: 'date',
      key1: 'second_storage_from_date',
    },
    {
      id: 9,
      field: 'second_storage_to_date',
      section: 'Advance Charges Review',
      required: false,
      editable: true,
      readable: true,
      showWarning: false,
      label: 'Second Storage To Date',
      type: 'label',
      format: 'date',
      key1: 'second_storage_to_date',
    },
    {
      id: 10,
      field: 'second_storage_rate',
      section: 'Advance Charges Review',
      required: false,
      editable: true,
      readable: true,
      showWarning: false,
      label: 'Second Storage Rate (Per Day)',
      type: 'label',
      format: 'currency',
      key1: 'second_storage_rate',
    },
    {
      id: 11,
      field: 'second_storage_amount',
      section: 'Advance Charges Review',
      required: false,
      editable: true,
      readable: true,
      showWarning: false,
      label: 'Second Storage Amount',
      type: 'label',
      format: 'currency',
      key1: 'second_storage_amount',
    },
    {
      id: 12,
      field: 'negotiated_storage',
      section: 'Advance Charges Review',
      required: false,
      editable: true,
      readable: true,
      showWarning: false,
      label: 'Flat/Negotiated Storage',
      type: 'label',
      format: 'currency',
      key1: 'negotiated_storage',
    },
    {
      id: 13,
      field: 'estimating_fee',
      section: 'Advance Charges Review',
      required: false,
      editable: false,
      readable: true,
      showWarning: false,
      label: 'Teardown/Estimating Fee',
      type: 'label',
      key1: 'estimating_fee',
      format: 'currency',
    },
    {
      id: 14,
      field: 'misc_fee',
      section: 'Advance Charges Review',
      required: false,
      editable: true,
      readable: true,
      showWarning: false,
      label: 'Miscellaneous',
      type: 'label',
      format: 'currency',
      key1: 'misc_fee',
    },
    {
      id: 15,
      field: 'tax',
      section: 'Advance Charges Review',
      required: false,
      editable: true,
      readable: true,
      showWarning: false,
      label: 'Tax',
      type: 'label',
      key1: 'tax',
      format: 'currency',
    },
    {
      id: 16,
      field: 'total',
      section: 'Advance Charges Review',
      required: false,
      editable: false,
      readable: true,
      showWarning: false,
      label: 'Total',
      type: 'label',
      format: 'currency',
      key1: 'total',
    },
    {
      id: 17,
      field: 'attachment',
      section: 'Advance Charges Review',
      required: false,
      editable: true,
      readable: true,
      showWarning: false,
      label: 'Upload Document',
      type: 'multiImage',
      key1: 'attachment',
      documentType: 'ADVANCE_CHARGE_RECEIPT',
    },
    {
      id: 18,
      field: 'hasCharges',
      section: 'Payment Options',
      required: true,
      editable: true,
      readable: true,
      showWarning: false,
      label: 'Charges Collected?',
      type: 'buttons',
      optionKeys: 'Yes|No',
      key1: 'hasCharges',
    },
    {
      id: 19,
      field: 'paymentType',
      section: 'Payment Options',
      required: ['==', { type: 'var', value: ['18'] }, { type: 'string', value: 'Yes' }],
      editable: true,
      readable: ['==', { type: 'var', value: ['18'] }, { type: 'string', value: 'Yes' }],
      showWarning: false,
      label: 'Select Payment Type',
      type: 'accessory',
      sortable: false,
      multiselect: false,
      key1: 'paymentType',
      referenceDataKey: 'paymentType',
      scrollOnSave: { sectionIndex: 1, itemIndex: 2 },
    },
    {
      id: 20,
      field: 'creditCardNumber',
      section: 'Payment Options',
      required: [
        'and',
        ['==', { type: 'var', value: ['18'] }, { type: 'string', value: 'Yes' }],
        ['==', { type: 'var', value: ['19'] }, { type: 'string', value: 'Credit Card' }],
      ], // value == card
      editable: true,
      readable: [
        'and',
        ['==', { type: 'var', value: ['18'] }, { type: 'string', value: 'Yes' }],
        ['==', { type: 'var', value: ['19'] }, { type: 'string', value: 'Credit Card' }],
      ], // value == card
      showWarning: false,
      label: 'Card Last four digits',
      type: 'text',
      autoCapitalize: 'sentences',
      keyboardType: 'numeric',
      key1: 'creditCardNumber',
      validations: {
        maxLength: 4,
        match: 'numeric',
      },
    },
    {
      id: 21,
      field: 'creditCardName',
      section: 'Payment Options',
      required: [
        'and',
        ['==', { type: 'var', value: ['18'] }, { type: 'string', value: 'Yes' }],
        ['==', { type: 'var', value: ['19'] }, { type: 'string', value: 'Credit Card' }],
      ], // value == card
      editable: true,
      readable: [
        'and',
        ['==', { type: 'var', value: ['18'] }, { type: 'string', value: 'Yes' }],
        ['==', { type: 'var', value: ['19'] }, { type: 'string', value: 'Credit Card' }],
      ], // value == card
      showWarning: false,
      label: 'Name on Card',
      type: 'text',
      validations: {
        maxLength: 20,
      },
      autoCapitalize: 'sentences',
      key1: 'creditCardName',
    },
    {
      id: 22,
      field: 'creditCardTotal',
      section: 'Payment Options',
      required: [
        'and',
        ['==', { type: 'var', value: ['18'] }, { type: 'string', value: 'Yes' }],
        ['==', { type: 'var', value: ['19'] }, { type: 'string', value: 'Credit Card' }],
      ], // value == card
      editable: true,
      readable: [
        'and',
        ['==', { type: 'var', value: ['18'] }, { type: 'string', value: 'Yes' }],
        ['==', { type: 'var', value: ['19'] }, { type: 'string', value: 'Credit Card' }],
      ], // value == card
      showWarning: false,
      label: 'Total Amount paid',
      type: 'text',
      autoCapitalize: 'sentences',
      keyboardType: 'numeric',
      isCurrency: true,
      key1: 'creditCardTotal',
      validations: {
        match: 'currency',
      },
    },
    {
      id: 23,
      field: 'creditCardDate',
      section: 'Payment Options',
      required: [
        'and',
        ['==', { type: 'var', value: ['18'] }, { type: 'string', value: 'Yes' }],
        ['==', { type: 'var', value: ['19'] }, { type: 'string', value: 'Credit Card' }],
      ], // value == card
      editable: true,
      readable: [
        'and',
        ['==', { type: 'var', value: ['18'] }, { type: 'string', value: 'Yes' }],
        ['==', { type: 'var', value: ['19'] }, { type: 'string', value: 'Credit Card' }],
      ], // value == card
      showWarning: false,
      label: 'Date paid',
      type: 'date',
      key1: 'creditCardDate',
    },
    {
      id: 24,
      field: 'creditCardImage',
      section: 'Payment Options',
      required: [
        'and',
        ['==', { type: 'var', value: ['18'] }, { type: 'string', value: 'Yes' }],
        ['==', { type: 'var', value: ['19'] }, { type: 'string', value: 'Credit Card' }],
      ], // value == check
      editable: true,
      readable: [
        'and',
        ['==', { type: 'var', value: ['18'] }, { type: 'string', value: 'Yes' }],
        ['==', { type: 'var', value: ['19'] }, { type: 'string', value: 'Credit Card' }],
      ], // value == check
      showWarning: false,
      label: 'Image of Card',
      type: 'multiImage',
      key1: 'creditCardImage',
      documentType: 'ADVANCE_CHARGE_RECEIPT',
    },
    {
      id: 25,
      field: 'checkNumber',
      section: 'Payment Options',
      required: [
        'and',
        ['==', { type: 'var', value: ['18'] }, { type: 'string', value: 'Yes' }],
        ['==', { type: 'var', value: ['19'] }, { type: 'string', value: 'Check' }],
      ], // value == check
      editable: true,
      readable: [
        'and',
        ['==', { type: 'var', value: ['18'] }, { type: 'string', value: 'Yes' }],
        ['==', { type: 'var', value: ['19'] }, { type: 'string', value: 'Check' }],
      ], // value == check
      showWarning: false,
      label: 'Check Number',
      type: 'text',
      autoCapitalize: 'sentences',
      keyboardType: 'numeric',
      key1: 'checkNumber',
      validations: {
        match: 'numeric',
      },
    },
    {
      id: 28,
      field: 'checkTotal',
      section: 'Payment Options',
      required: [
        'and',
        ['==', { type: 'var', value: ['18'] }, { type: 'string', value: 'Yes' }],
        ['==', { type: 'var', value: ['19'] }, { type: 'string', value: 'Check' }],
      ], // value == check
      editable: true,
      readable: [
        'and',
        ['==', { type: 'var', value: ['18'] }, { type: 'string', value: 'Yes' }],
        ['==', { type: 'var', value: ['19'] }, { type: 'string', value: 'Check' }],
      ], // value == check
      showWarning: false,
      label: 'Total Amount',
      type: 'text',
      autoCapitalize: 'sentences',
      keyboardType: 'numeric',
      isCurrency: true,
      key1: 'checkTotal',
      validations: {
        match: 'currency',
      },
    },
    {
      id: 29,
      field: 'checkImage',
      section: 'Payment Options',
      required: [
        'and',
        ['==', { type: 'var', value: ['18'] }, { type: 'string', value: 'Yes' }],
        ['==', { type: 'var', value: ['19'] }, { type: 'string', value: 'Check' }],
      ], // value == check
      editable: true,
      readable: [
        'and',
        ['==', { type: 'var', value: ['18'] }, { type: 'string', value: 'Yes' }],
        ['==', { type: 'var', value: ['19'] }, { type: 'string', value: 'Check' }],
      ], // value == check
      showWarning: false,
      label: 'Image of Check',
      type: 'multiImage',
      key1: 'checkImage',
      documentType: 'ADVANCE_CHARGE_RECEIPT',
    },
    {
      id: 30,
      field: 'cashTotal',
      section: 'Payment Options',
      required: [
        'and',
        ['==', { type: 'var', value: ['18'] }, { type: 'string', value: 'Yes' }],
        ['==', { type: 'var', value: ['19'] }, { type: 'string', value: 'Cash' }],
      ], // value == cash
      editable: true,
      readable: [
        'and',
        ['==', { type: 'var', value: ['18'] }, { type: 'string', value: 'Yes' }],
        ['==', { type: 'var', value: ['19'] }, { type: 'string', value: 'Cash' }],
      ], // value == cash
      showWarning: false,
      label: 'Total Amount',
      type: 'text',
      autoCapitalize: 'sentences',
      keyboardType: 'numeric',
      isCurrency: true,
      key1: 'cashTotal',
      validations: {
        match: 'currency',
      },
    },
    { id: 31, section: 'Payment Options', field: 'blank', type: 'bottomBuffer', readable: true },
  ],
};
