export default {
  vehicleDetails: [
    {
      id: 1,
      field: 'driverSignature',
      section: 'Acknowledgement',
      required: true,
      editable: true,
      readable: true,
      showWarning: false,
      label: 'Driver Signature',
      type: 'signature',
      key1: 'driverSignature',
    },
    {
      id: 2,
      field: 'driverPrint',
      section: 'Acknowledgement',
      required: true,
      editable: true,
      readable: true,
      showWarning: false,
      label: 'Driver Print Name',
      type: 'text',
      autoCapitalize: 'words',
      key1: 'driverPrint',
      validations: {
        maxLength: 20,
      },
    },
    {
      id: 3,
      field: 'otherRefusedSign',
      section: 'Acknowledgement',
      required: true,
      editable: true,
      readable: true,
      showWarning: false,
      label: 'Shop/Owner Refused to Sign',
      type: 'buttons',
      optionKeys: 'Yes|No',
      key1: 'otherRefusedSign',
    },
    {
      id: 4,
      field: 'ownerSignature',
      section: 'Acknowledgement',
      required: ['==', { type: 'var', value: ['3'] }, { type: 'string', value: 'No' }],
      editable: true,
      readable: true,
      showWarning: false,
      label: 'Shop/Owner Signature',
      type: 'signature',
      key1: 'ownerSignature',
    },
    {
      id: 5,
      field: 'ownerPrint',
      section: 'Acknowledgement',
      required: true,
      editable: true,
      readable: true,
      showWarning: false,
      label: 'Shop/Owner Print Name',
      type: 'text',
      autoCapitalize: 'words',
      key1: 'ownerPrint',
      validations: {
        maxLength: 20,
      },
    },
    {
      id: 6,
      field: 'datePickedUp',
      section: 'Acknowledgement',
      required: true,
      editable: true,
      readable: true,
      showWarning: false,
      label: 'Date Picked Up',
      type: 'date',
      key1: 'datePickedUp',
    },
    {
      id: 7,
      field: 'notes',
      section: 'Acknowledgement',
      required: true,
      editable: true,
      readable: true,
      showWarning: false,
      label: 'Additional Notes',
      type: 'comments',
      key1: 'notes',
      validations: {
        maxLength: 100,
      },
    },
  ],
};
