import { map } from 'ramda';
import { renameKeys } from 'utils/commonUtils';

const issuesQueueMap = {
  dispatch_assignment_detail_id: 'dispatchAssignmentDetailId',
  dispatch_assignment_id: 'dispatchAssignmentId',
  trip_distance: 'tripDistance',
  lot_stage_code: 'lotStageCode',
  lot_number: 'lotNumber',
  payment_mode: 'paymentMode',
  trip_type_code: 'tripTypeCode',
  promised_date: 'promisedDate',
  lot_type: 'vehicleType',
  lot_model_year: 'year',
  lot_make: 'make',
  lot_model: 'model',
  lot_description: 'description',
  responsible_facility_id: 'responsibleFacilityId',
  dispatch_status_code: 'dispatchStatusCode',
  created_date: 'createdDate',
  last_updated_date: 'lastUpdatedDate',
  message_header_id: 'messageHeaderId',
  message_category_code: 'message_category_code',
  message_type_code: 'message_type_code',
  message_subtype_code: 'message_subtype_code',
  created_by_id: 'createdById',
  created_by_type: 'createdByType',
  current_entity_id: 'currentEntityId',
  current_entity_type: 'currentEntityType',
  message_acknowledged_flag: 'messageAcknowledgedFlag',
  message_acknowledged_by_id: 'messageAcknowledgedById',
  message_status: 'messageStatus',
  location_address_line1: 'locationAddressLine1',
  location_address_line2: 'locationAddressLine2',
  location_city: 'locationCity',
  location_state: 'locationState',
  location_name: 'locationName',
  location_zip: 'locationZip',
  dispatch_status_description: 'dispatchStatusDescription',
  due_today_flag: 'dueTodayFlag',
  message_category_description: 'messageCategoryDescription',
  message_type_description: 'messageTypeDescription',
  message_subtype_description: 'messageSubtypeDescription',
  available_actions: 'availableActions',
  created_by_name: 'createdByName',
  created_by_comment: 'createdByComment',
  current_entity_name: 'currentEntityName',
};

export const issueMapper = renameKeys(issuesQueueMap);
export const issuesQueueMapper = data => map(issueMapper)(data);
