// @flow
/* eslint-disable max-len */

export const LOT_STATUSES = {
  // awaiting_trip_build: 200
  // awaiting_assignment: 210
  AWAITING_VENDOR_ACKNOWLEDGEMENT: 220,
  AWAITING_GROUP_ACKNOWLEDGEMENT: 230,
  AWAITING_DRIVER_ACKNOWLEDGEMENT: 240,
  AWAITING_IN_PROGRESS: 250, // # Acknowledged
  AWAITING_FORM_SUBMISSION: 260,
  AWAITING_ARRIVAL: 270,
  AWAITING_CHECKIN: 280,
  AWAITING_TRIP_VERIFICATION: 290,
  COMPLETED: 300,
};

export const CASH_STATUSES = {
  AWAITING_CHECK_GENERATION: 1,
  AWAITING_CASH_READY: 2,
  AWAITING_CASH_PICKUP: 3,
  AWAITING_CASH_FROM_DRIVER: 4,
  COMPLETED: 5,
};

export const bucketToStatusMap = {
  assigned: [
    LOT_STATUSES.AWAITING_VENDOR_ACKNOWLEDGEMENT,
    LOT_STATUSES.AWAITING_GROUP_ACKNOWLEDGEMENT,
    LOT_STATUSES.AWAITING_DRIVER_ACKNOWLEDGEMENT,
  ],
  accepted: LOT_STATUSES.AWAITING_IN_PROGRESS,
  inProgress: LOT_STATUSES.AWAITING_FORM_SUBMISSION,
  inTransit: LOT_STATUSES.AWAITING_ARRIVAL,
  completed: [
    LOT_STATUSES.AWAITING_CHECKIN,
    LOT_STATUSES.AWAITING_TRIP_VERIFICATION,
    LOT_STATUSES.COMPLETED,
  ],
};

export type LotStatusTypes = 220 | 230 | 240 | 250 | 260 | 270 | 280 | 290 | 300;

export const TRANSITION_ACTIONS = {
  ACKNOWLEDGE: 'acknowledge',
  IN_PROGRESS: 'in_progress',
  DROPOFF: 'dropoff',
};
