# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'CopartTransporter' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CopartTransporter
  pod 'GoogleMaps'
  
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Messaging'
  
  pod 'Fabric'
  pod 'Crashlytics'

end
