// @flow

import type { LotStatusTypes } from 'constants/Lot';

import type {
  LotTripTypes,
  LotTripStatusCode,
  LotTowTypes,
  LotAddress,
  LotPaymentModes,
} from './LotAttributes';

// TODO: Update type according to the latest service response
export type Lot = {
  vendor_path_flag: 0 | 1,
  dispatch_group_path_flag: 0 | 1,
  vendor_personnel_path_flag: 0 | 1,
  dispatchAssignmentDetailId: number,
  active_issue_flag: boolean,
  is_partial_trip_lot: boolean,
  lotNumber: number,
  messageTypeDescription: ?string,
  partial_trip_comments: ?string,
  cashTag: '',
  clientUpdateTime: '2018-01-15T16: 47: 14Z',
  damageCode: string,
  description: string,
  destination: LotAddress,
  destinationLocationId: string,
  isPartialTripLot: boolean,
  isTowable: 'Y',
  jobUpdateTime: '2018-01-10T19: 38: 27Z',
  lotStage: number,
  lotTripId: number,
  make: string,
  model: string,
  number: string,
  pickupPhoneNumber: {
    areaCode: '713',
    extension: '',
    line: '5234774',
  },
  promisedTripDate: '2016-11-15',
  tripId: string,
  scheduledTimeFrom: '',
  scheduledTimeTo: '',
  source: LotAddress,
  sourceLocationId: string,
  subhaulerUser: string,
  suffix: string,
  towType: LotTowTypes,
  trackupdatedBy: string,
  tripStatus: LotTripStatusCode,
  tripType: LotTripTypes,
  tripZone: number,
  updateByUser: string,
  updatedBy: string,
  vehicleType: string,
  yardNumber: number,
  year: number,
  forms: {},
  status: LotStatusTypes,
  messageStatus: 'I' | 'A',
  availableActions?: Array<string>,
  paymentMode: LotPaymentModes,
  response_comments?: string,
};
